Add solution to ex38 of bases cs
VideojogosLusofona/lp1_exercicios pull request #100
Opened 2019-04-13 11:18 UTC by PmaiWoW

2019-04-13 14:52 UTC, nunofachada requested changes
Pedro, respondendo à questão que me enviaste no Moodle: não podes alterar o `Main`. Nem precisas, uma vez que o _array_ é um tipo de referência, pelo que os respetivos conteúdos estão na _heap_ e não na _stack_...

Outra coisa, no método `CreateNumbersToN()` tens lá uma operação em que faltam os espaços em torno do operador `+`.

2019-04-14 19:11 UTC, PmaiWoW commented
Alterações foram feitas, Main() fica igual ao do enunciado, método Reverse não retorna nada pois, após igualar os valores das posições da última para a primeira de numbers às de reverseArray, iguala cada posição de numbers à posição equivalente de reverseNumbers, ficando então com os valores do array numbers invertidos, não sendo necessário então fazer qualquer retorno.

2019-04-14 20:24 UTC, nunofachada requested changes
Olá Pedro, a solução está correta, mas podes remover o `Main()` da solução pois é igual ao `Main()` da pergunta.

2019-04-14 21:53 UTC, fakenmc commented
Obrigado Pedro, solução aceite.

2019-04-14 21:53 UTC, merged

2019-04-14 21:57 UTC, fakenmc commented
Pedro, atenção que estes _commits_ foram feitos com a configuração do Git mail feita, nomeadamente com um email inválido, pelo que não serão atualizadas na página [contributors](https://github.com/VideojogosLusofona/lp1_exercicios/graphs/contributors).

2019-04-14 22:08 UTC, PmaiWoW commented
Pois, ficou assim quando instalei um git client que me foi recomendado quando tive uns problemas com os ramos e tenho de reconfigurar o Git porque aquilo mudou-me a configuração...

2019-04-14 22:31 UTC, PmaiWoW commented
A configuração já foi corrigida, futuros pull requests já serão feitos normalmente