Tentativa de resolução do ex 10 de 03_poo
VideojogosLusofona/lp1_exercicios pull request #108
Opened 2019-04-15 19:15 UTC by JBernardoRebelo

Estou com problemas na parte de mostrar os elementos da enumeração, neste momento só consigo mostrar o 1º elemento. Se não houverem muitos problemas posso acrescentar mais carros e testes a estes.

2019-04-15 20:17 UTC, nunofachada requested changes
* Sendo a enumeração um tipo que deve ser partilhado e estar disponível entre as várias classes do programa, a mesma não deveria estar dentro de `Car`. Por isso é que não consegues aceder aos seus valores a partir de `TestCar`.
* Cada um dos tipos, `Car`, `TestCar` e `Fuel`, deve estar num ficheiro à parte. Podes ilustrar isso colocando cada tipo num bloco de código separado.
* A variável de instância `_fuelType` não deve ser pública. Além disso, nomes de variáveis começados por _underscore_ são por vezes usados em variáveis privadas, mas nunca variáveis públicas.
* Em termos de organização de classes, deves separar claramente variáveis de instância e variáveis `static`, ou seja, não as deves misturar, como é o caso.
* No enunciado não era referido que devias ter aqueles `Console.WriteLines()` dentro dos métodos de `Car`. Se quisesses usar esta classe no Unity tinhas que limpar essa parte do código, portanto é má prática meter `Console.WriteLines()` só porque sim. No `Main()` utilizas `Console.WriteLines()` porque queres testar a classe, nada mais.
* No método `SetMaxSpeed()` não é necessário acederes à variável `maxSpeed` através de `Car`, pois já estás em `Car`. Aliás, no método `GetMaxSpeed()` não o fazes.

2019-04-15 20:56 UTC, JBernardoRebelo commented
Professor, o problema com a enum é que por alguma razão só consigo aceder ao seu primeiro valor sem dar, isso está-me a deixar um pouco confuso.

2019-04-15 21:50 UTC, nunofachada requested changes
* Remove os `usings` desnecessários em cada um dos ficheiros.
* Insere uma linha em branco entre cada bloco de código.
* Os métodos `Accelerate()` e `Break()` podem ser simplificados. Seja qual for o caso vais sempre devolver a velocidade... além de que as boas práticas dizem que só deves ter um `return`.
* Na instanciação dos carros no `Main()` podes usar os valores da enumeração em vez de passares inteiros para especificares o tipo de combustível.
* Insere linha em branco entre o último bloco de código e a tua assinatura.

2019-04-15 21:53 UTC, fakenmc commented
Para acederes aos valores da enumeração basta fazeres por exemplo `Fuel.Electric` ou `Fuel.LPG`, etc.

2019-04-16 12:54 UTC, nunofachada requested changes
Olá João, a solução está boa, mas a classe `TestCar` precisa de um `using` para fazer uso do `Console.WriteLine()`...

2019-04-16 12:59 UTC, merged

2019-04-16 12:59 UTC, fakenmc commented
Obrigado João, solução aceite.