1º tentativa soluçao para poo 06
VideojogosLusofona/lp1_exercicios pull request #113
Opened 2019-04-18 03:04 UTC by RafaelCS-Aula

Apercebi-me que há outra maneira de fazer a enumeração e o método `Hit()` que não envolveria um número de conversões. Envio esta porque funciona, para saber se é aceitável/está bem documentada o suficiente e porque foi a primeira em que pensei.

2019-04-18 11:06 UTC, nunofachada requested changes
* Falta enunciado.
* Enumeração não tem que ser com _bits_, uma vez que os NPCs não podem ser mais do que um tipo (tal não é mencionado no enunciado, e pelo tipo de NPCs percebes que não faz sentido serem _Minions_ e _Bosses_ ao mesmo tempo). Além disso os valores da enumeração podem facilitar a implementação do método `Hit()`.
* Porque razão `TakeHit()`, `Faster()` e `Slower()` devolvem um `float`, se tal não é pedido no enunciado?
* O código do método `Hit()` é demasiado complexo, com demasiadas conversões. Este tipo de código é capaz de reduzir as _FPS_ de um jogo para metade...

2019-04-18 14:10 UTC, RafaelCS-Aula commented
Eu pus esses métodos a devolverem `float` para poder ver os valores finais das variáveis no ecrâ. Mudei neste próximo commit para `void`

2019-04-19 16:09 UTC, nunofachada requested changes
* Embora estejam corretos, existe uma forma mais compacta de alterares a velocidade nos métodos `Faster()` e `Slower()`, apenas com o operador `*=`.
* No método `Hit()` porque razão alteraras o `damage` do NPC se tal não é pedido no enunciado?
* No `Main()` seria interessante teres uns `Console.WriteLines()` a mais para mostrar a diferença de velocidades à medida que vais aplicando os métodos, bem como a potência dos golpes. Neste momento apenas aparece no ecrã que eles morreram.
* Remove linhas em branco desnecessárias antes dos finais dos blocos de código.

2019-04-19 22:08 UTC, RafaelCS-Aula commented
> 
>Embora estejam corretos, existe uma forma mais compacta de alterares a velocidade nos métodos `Faster()` e `Slower()`, apenas com o operador `*=`.

Não percebo como, se o método fizer `_speed *= 0.1` não resulta no que o enunciado pede. 
Pelo que percebi pelo enunciado eu devo só retirar 10%  de `_speed` a si mesma.

2019-04-19 22:57 UTC, nunofachada requested changes
* O nome das variáveis deve começar com minúscula, não é o caso de `William`, etc.
* As variáveis devem ser declaradas no início dos métodos ou blocos. No teu `Main()` elas vão sendo declaradas ao longo do código. Repara que declaradas não é a mesma coisa que serem inicializadas.
* O código não compila devido a um cifrão a mais no sítio errado.
* Se fizeres `speed *= 0.9;`, o que acontece? E `speed *= 1.1;`?
* Tens algum código mal identado. As continuações de _string_ são indentadas 4 espaços a mais do que a linha onde a _string_ começa, por exemplo, devia ser:

```cs
Console.WriteLine($"Jimmy is a Soldier with:\n" +
    $" {Jimmy.GetEnergy()} Energy\n" +
    $" {Jimmy.GetSpeed()} Speed\n" +
    $" {Jimmy.GetBaseDamage()} Damage");
```

2019-04-20 15:17 UTC, fakenmc commented
Obrigado Rafael, solução aceite.

2019-04-20 15:17 UTC, merged