Resolução do Exercício 02 de POO
VideojogosLusofona/lp1_exercicios pull request #116
Opened 2019-04-21 13:16 UTC by ThomasFranque

Boa tarde, 
tenho so uma pergunta em relação ao exercício.
Esta classe `Stack` é o equivalente ao `Pop()` e `Push()` de C?

2019-04-21 17:05 UTC, nunofachada requested changes
Olá Tomás,

* A solução está boa, mas como requer um `using` específico, sugiro que incluas a classe toda, e não apenas os métodos.
* Sobre a tua pergunta:
  * A estrutura de dados _stack_, bem como as suas operações _push_ e _pop_, são uma forma abstrata de guardar dados, ao estilo LIFO (_last in, first out_).
  * Se clicares no _link_ para o Wikipedia que coloquei no enunciado, percebes que a estrutura de dados _stack_ não está associada a uma linguagem de programação específica, embora seja possível de implementar em qualquer linguagem.
  * Algumas linguagens de programação já contêm uma _stack_ pronta a usar, como é o caso do C# e do Java. No C# podem simplesmente usar a _stack_ disponível no _namespace_ `System.Collections` (ou melhor ainda, a _stack_ disponível em `System.Collections.Generic`, que falaremos mais à frente).
  * A linguagem C não inclui nenhuma _stack_ pronta a usar, tens de ser tu a implementar, ou então usas uma biblioteca de terceiros que disponibilize uma implementação. Como é uma estrutura de dados muito simples, é possível que tenhas dado isso em IC, mas no sentido de fazerem vocês uma, que depois usam à medida.
  * De qualquer das formas fazer uma classe `Stack` de raiz em C# é um bom exercício...

2019-04-21 22:04 UTC, ThomasFranque commented
Ok, obrigado pela explicação. 
Gostaria de tentar fazer uma classe `Stack`, de raiz, em C# para treino, por onde devo começar a olhar? Devo olhar para a documentação da classe já existente e tentar replicar ou, em aulas mais à frente, daremos a matéria necessária para tal? (se é que não existe já um exercício no repositório)

2019-04-22 11:26 UTC, merged

2019-04-22 11:42 UTC, fakenmc commented
Olá Tomás, solução aceite.
Quanto a implementares a tua própria _stack_, não temos previsto nenhum exercício para tal, pois nas aulas temos que estar focados naquilo que mais interessa para os jogos. No entanto é sempre um bom exercício de aprendizagem tentar fazer uma, de modo a percebermos como as coisas funcionam mesmo. Se quiseres experimentar fazer, e já demos a matéria suficiente para isso, tens duas formas principais de o fazer. Em ambos os casos precisas de uma classe que represente uma _stack_, por exemplo `MyStack`, que tem pelo menos dois métodos: `Push()` e `Pop()` (podes inspirar-te na classe `Stack` do C# para as declarações/assinaturas destes métodos). As duas abordagens são:

1. Na classe `MyStack` guardas os conteúdos da _stack_ num _array_ de `object` (o tipo `object` permite lá guardares o quiseres, `int`, etc - esta parte da matéria falaremos melhor mais à frente). Tens de guardar o índice do elemento mais recente guardado no _array_ e pode ser necessário aumentares o tamanho do _array_ à medida que a _stack_ cresce (vê na API de `System.Array` métodos que te permitam alterar o tamanho de um _array_).
2. Na outra abordagem (mais eficiente em termos de ocupação de memória), além da classe `MyStack` precisas de outra chamada por exemplo `MyStackElement`, onde em cada instância da qual vais ter: 1) um elemento a guardar na _stack_; e, 2) uma referência para a próxima instância de `MyStackElement`, que contém o próximo elemento guardado na _stack_, etc. Neste caso, na classe `MyStack` apenas guarda uma referência para a instância de `MyStackElement` no topo da _stack_.

Isto está explicado muito por alto, se quiseres posso dar-te mais informação sobre uma ou outra abordagem.

2019-04-23 12:16 UTC, ThomasFranque commented
Olá, irei então ver disso quando puder.
Obrigado!