Bases cs, Exercício 37, Inacabado
VideojogosLusofona/lp1_exercicios pull request #117
Opened 2019-04-24 11:51 UTC by RodrigoPrinheiro

Tenho umas dúvida sobre a parte da geração dos items.
#### Dúvida 1
O professor diz que as probabilidades estão cumulativamente na mini tabela apresentada no enunciado, no entanto Armas e Inimigos têm a mesma probabilidade, significando, cumulativamente, que um desses não terá quaisquer probabilidades de ser escolhido. É suposto ser assim? Ou há um erro na tabela?

#### Dúvida 2
Mais uma dúvida, se então a tabela está correta, gerando um número de 0 a 1 como é que iria escolher mais que um item calhando por exemplo Comida + Armadilha? Isto a ver com a dúvida das probabilidades explicada anteriormente.

Tentei uma implementação de 0 a 2,3 mas assim chego ao problema de que apenas 1 item pode estar em cada célula da matriz.

2019-04-24 13:30 UTC, fakenmc commented
Olá Rodrigo,

Para cada célula e para cada item lanças um número de 0 a 1. Se for menor que a probabilidade desse item, então o item irá existir na célula. Podes até ter 4 itens diferentes numa única célula, embora seja altamente improvável.

2019-04-25 19:18 UTC, nunofachada requested changes
Olá Rodrigo, algumas notas para melhorares este exercício:

* A enumeração não é *enumerable flags*, ou seja, não é uma enumeração de bits. Assim sendo, não vai funcionar como esperas.
* A probabilidade 1 é igual a 100%. Probabilidade de 1% é igual a 0.01. E por ai fora.
* Porque razão tens aquele terceiro ciclo interno, o da letra _k_?
* Nos comentários é boa prática teres um espaço entre `//` e o comentário propriamente dito. Ou seja, deve ser por exemplo `// Variáveis do programa` e não `//Variáveis do programa`.
* Da mesma forma, os comentários devem começar com maiúscula, como se fossem uma frase (fizeste isso em todos, excepto num).
* Os cabeçalhos **Problema** são de nível 2 (e não nível 1).
* Deve haver sempre uma linha em branco após todos os cabeçalhos.

2019-04-26 15:49 UTC, RodrigoPrinheiro commented
Boa tarde professor, primeiro que tudo obrigado pelo feedback.
Enviei o commit com as modificações requisitadas, no entanto fiquei na dúvida:
 - As percentagens ficam baixíssimas se estiver a contar por percentagem;
 - Pela forma que o professor pede as percentagens no enunciado fica dúbio dizer que são cumulativas, a não ser que as tenha feito mal;
 - Da forma como tenho não poderá existir no mesmo quadrado mais que um item, daí por isso é que tinha o _for loop_ com o _k_ 4 vezes, sendo isto para cada item, como pedido, mas presumo que a implementação não tenha sido a melhor de facto...

2019-04-26 18:41 UTC, nunofachada requested changes
Olá Rodrigo, está melhor mas ainda não está 100%. Algumas questões para analisares:

* A enumeração `Items` tem de estar no mesmo _namespace_ que a classe `Program`.
* A enumeração `Items` requer um `using` específico por causa do atributo `[Flags]`.
* É boa ideia teres colocado documentação XML, mas para o fazer tem de ser em todo o lado. Ou seja, deves documentar todos os métodos e tipos (classes/enumerações).
* No método `GenerateItems()` porque razão verificas se está lá cada um dos itens? De certeza que não vai estar, pois cada célula da grelha está a ser gerada pela primeira vez.
* Os itens devem existir cumulativamente em cada célula da grelha. Ou seja, não faz sentido estares a usar o `else if`. Aliás, se pensares bem na lógica, esses `else ifs` nunca vão ser executados (e é a razão pela qual só consegues gerar comida `!`).
* Já que desenhas o topo, podes também desenhar a base. Até podes ter um método só para desenhar uma linha e escusas de repetir código.

2019-04-27 18:02 UTC, nunofachada requested changes
Está quase, apenas pequenos detalhes:

* As variáveis devem ser declaradas no início do método ou do bloco, e nem sempre fazes isso. Nota que declarar uma variável e inicializa-la são duas coisas diferentes, que apesar de poderem ser feitas numa só linha também podem ser feitas em linhas separadas.
* Para cada item tens de obter uma nova probabilidade, caso contrário as probabilidades não são independentes. Em concreto: i) se a probabilidade de teres comida se verificar, ficas com 50% de probabilidade de teres armas e inimigo, e com 30% de probabilidade de teres armadilhas; ii) se a probabilidade de teres armas se verificar, então vais automaticamente ter inimigo (pois é a mesma probabilidade que estás a testar para as duas situações); iii) etc...

2019-04-27 20:23 UTC, fakenmc commented
Obrigado Rodrigo, solução aceite.

2019-04-27 20:23 UTC, merged