Resolução do exercício POO_12
VideojogosLusofona/lp1_exercicios pull request #119
Opened 2019-04-26 17:54 UTC by ThomasFranque

2019-04-26 19:19 UTC, nunofachada requested changes
Olá Tomás, este exercício requer a matéria da próxima aula para ser completado, nomeadamente **Propriedades**. O respetivo slide já está no Moodle. Em todo o caso deixo algumas sugestões para ires melhorando o exercício:

*  O cabeçalho **Classe Dog.cs** não faz muito sentido. `Dog.cs` é o nome do ficheiro, a classe chama-se apenas `Dog`. Faz como fizeste no cabeçalho do `Program.cs`, ou muda os dois cabeçalhos para **Classe *NomeDaClasse*  **.
* A inicialização de variáveis de instância deve ser feita no construtor. Tal não está a acontecer no caso da variável `random`.
* Qual é a visibilidade da variável de classe `barks`?
* A variável `barks` alguma vez muda? Senão muda, é boa prática torna-la `const` ou `readonly`. Falaremos disto em mais detalhe na aula 9 (que é a aula a seguir à próxima).
* O enunciado pode ser um pouco vago, mas numa coisa é específico: apenas o método para ladrar deve imprimir algo no ecrã...
* ...e se assim for, o teu `Main()` pouco mostra no ecrã, excepto o ladrar. No `Main()` deves obter os valores dos campos do cão e mostrar como os mesmos se alteram após invocares os métodos.
  * Aqui entra a matéria nova, pois na aula passada aprendemos a obter esses valores usando _getters_. No entanto neste exercício deves usar propriedades, que daremos na próxima aula. Dá uma vista de olhos no slide da próxima aula e tenta ver se consegues resolver o exercício dessa forma.
* A tua lógica na saciação não faz muito sentido. O que tu queres é que a saciação nunca ultrapasse 1, mas no teu `if` pode dar-se o caso do cão não comer absolutamente nada.
* O enunciado diz que deves devolver a velocidade. Neste momento esse método devolve `void`. 
* Já que tens dois construtores podias testar os dois no `Main()`.

2019-04-27 11:49 UTC, ThomasFranque commented
Bom dia professor, tentei resolver o exercício conforme o que foi pedido, porém, não sei se era bem assim, o Visual Studio dava-me a mensagem _use auto property_ na variável `weight` mesmo sendo utilizada para calcular a velocidade.

2019-04-27 18:16 UTC, nunofachada requested changes
Olá Tomás, está melhor, mas ainda precisa de alguns ajustes:

* Porque razão não pode (e deve) `Weight` ser uma propriedade auto-implementada?
* Porque razão precisas da variável `satiation`? Não poderia ser uma propriedade auto-implementada (com `set` privado)? Ou melhor ainda, não poderia ser uma propriedade (normal) em que o `set` (privado) contivesse a lógica de manter o seu valor entre 0 e 1 (removendo essa lógica do método `Eat`)?
* Qual é a visibilidade das variáveis `barks` e `colors`?
* Existe algum código repetido entre os dois construtores. Que tal moveres o código repetido para um método e chamares esse método de ambos os construtores?

Ponto extra na avaliação dos exercícios se resolveres este exercício antes da próxima aula.

2019-04-29 10:42 UTC, nunofachada requested changes
Quase. Algumas coisas ainda a melhorar:

* Relativamente à propriedade `Satiation`:
  * Admito que o enunciado possa induzir em erro, mas uma propriedade com `private set` não é _read-only_. Para ser só de leitura, uma propriedade nem sequer pode ter `set`. Refiro isto pois no comentário referes que a propriedade é _read-only_. Vou corrigir o enunciado posteriormente à tua resolução.
  * A tua lógica do `if` não me parece correta. Visto que `value` é o valor final a atribuir à variável `satiation`, deves apenas verificar se `value <= 1` e não `satiation + value`. Concordas?
* Relativamente à duplicação de código nos construtores:
  * Aquele método `RandomAndSatiation()` (que se calhar podia ter um nome mais óbvio, tipo `Initialize()`) não poderia receber os valores para a cor, peso e altura, e inicializa-los ele? Para o efeito tens de permitir um `private set` nas respetivas propriedades (neste momento só têm `get`, ou seja, são _read-only_).
  * Uma vez que `barks` é _read-only_, aceita-se que possas inicializar os valores deste _array_ diretamente na declaração. Outra coisa, esta variável muda de instância para instância? Senão muda de instância de instância, devia ser uma variável de classe, e não de instância...
  * Pelo que percebo, a variável `colors` só é usada uma vez dentro de um dos construtores. Assim sendo, será que faz sentido ser uma variável de instância? Não poderia ser uma variável local desse construtor onde é usada?
* Na classe `Dog` cada uma das propriedades públicas deve ter documentação XML. Neste momento apenas a propriedade `Color` está documentada.
* A classe `Program` também deve estar documentada com comentários XML.

2019-04-29 21:17 UTC, ThomasFranque commented
Boa noite professor, consegui fazer tudo, penso eu, e antes de dar _commit_ queria só perguntar se o que estou a fazer aqui não é má prática.
Visto que vou precisar de um random para o construtor que não aceita argumentos, criei uma variável `Random newRandom` dentro desse construtor. No método `Initialize()` (antigo `RandomAndSatiation()`) aceito um parametro `Random`. Mas, no construtor que serão necessarios argumentos, `newRandom` não é criado. Seria esta solução aceitável:

### Construtor sem parâmetros
```cs
public Dog()
        {                    
            Random newRandom = new Random();
            // randWeight, randHeight, randColor defined meanwhile, using newRandom
            Initialize(randWeight, randHeight, randColor, newRandom);
        }
```

### Construtor com parâmetros

```cs
public Dog(double weight, double height, string color)
        {
            Initialize(weight, height, color, null);            
        }
```

### Método `Initialize()`

```cs
private void Initialize(double weight, double height, string color, 
            Random random)
        {
            // Checking if random was created
            if (random == null)
                this.random = new Random();
            else
                this.random = random;
        ...
```

Estaria a usar um `null` para verificar se já existe um uma variável _random_

2019-04-30 09:52 UTC, fakenmc commented
Olá Tomás, estive aqui a ver o teu código, e na forma como está feito, estamos perante um dos pouco casos em que até faz sentido inicializares a variável de instância `random` logo na declaração. Isto porque vai simplificar o código dos dois construtores, e tudo o que tornar o nosso código mais simples é Boa Prática™.

No entanto, regra geral é preferível inicializarmos as variáveis de instância/classe em construtores.

2019-04-30 19:08 UTC, nunofachada requested changes
Olá Tomás, a solução está a ficar muito boa, faltam apenas detalhes muito simples para poder aceitar:

* Continuo a perguntar: qual é a visibilidade da variável `barks`?
* Não são "Auto-properties", mas sim "auto-implemented properties".
* Não é inteiramente correto (nem inteiramente errado) dizer que uma propriedade retorna qualquer coisa. No entanto é 100% correto dizer que uma propriedade representa qualquer coisa (estilo uma variável).

2019-04-30 20:29 UTC, nunofachada requested changes
Últimos detalhes:

* Faltam os `using` necessários para o programa funcionar.
* Documentação do método `Main()`.

2019-05-01 17:08 UTC, nunofachada requested changes
Olá Tomás, peço desculpa por estar a chatear tanto com detalhes, mas pode ser bom para perceberes como eu vou querer que os projetos sejam entregues. Ainda faltam uns detalhes que só reparei agora:

* Falta documentar o argumento do método `Main()`.
* Tens uma linha em branco a mais no fim do primeiro bloco de código (ficheiro `Program.cs`).
* Tens `using` desnecessários na classe `Dog`. Provavelmente o Visual Studio avisa sobre isso.
* Não será "Dog constructor" em vez de "Constructor dog" nos comentários?
* No método `Eat()` porque não usas `random.NextDouble()` que dá-te logo um valor `double` entre 0 e 1? Se quiseres ajustar entre 0.1 e 0.8 (como tens agora), basta fazeres `0.1 + random.NextDouble() * 0.7`.
* Falta documentar o valor de retorno do método `Run()`.

2019-05-01 19:18 UTC, nunofachada requested changes
Falta a documentação do argumento (`args`) do método `Main()`...

2019-05-01 19:31 UTC, nunofachada approved these changes
Olá Tomás, fiz apenas algumas melhorias nos comentários (vê [aqui](https://github.com/VideojogosLusofona/lp1_exercicios/pull/119/commits/9420d6494d8b11005a561041e0f6e56059d7eec4) as alterações). Faltava também a documentação dos argumentos do método `Initialize()`.

De resto parabéns, ficou uma boa solução.

2019-05-01 19:31 UTC, merged

2019-05-01 19:39 UTC, ThomasFranque commented
Obrigado pela ajuda.