Solução 2 para Exercício 43 02_bases_cs
VideojogosLusofona/lp1_exercicios pull request #124
Opened 2019-05-06 23:52 UTC by AfonsoGR

2019-05-07 10:00 UTC, nunofachada requested changes
Olá Afonso,

A tua solução não é assim tão diferente da original, mas vou aceitar na mesma, pois a tua apesar de tudo usa operadores Lambda e tem comentários XML. No entanto para aceitar são preciso que completes a documentação XML, nomeadamente:

* Falta completar a _tag_ `<returns></returns>` dos métodos `Eat()`.
* Nos comentários referes as _enums_ `Terrains` e `BonusTerrains`, mas o nome delas é no singular.
* Falta documentar o método `Main()`.

2019-05-07 20:20 UTC, nunofachada requested changes
Está quase, falta documentares o parâmetro `args` do método `Main()`.

2019-05-08 23:09 UTC, AfonsoGR commented
Peço desculpa pela demora e agradeço a ajuda prestada.

2019-05-09 11:19 UTC, merged

2019-05-09 11:19 UTC, fakenmc commented
Obrigado Afonso, solução aceite.