1ª proposta de solução
VideojogosLusofona/lp1_exercicios pull request #128
Opened 2019-05-11 12:30 UTC by FPTheFluffyPawed

2019-05-11 17:59 UTC, nunofachada requested changes
Olá Inácio, as respostas estão corretas, mas gostava que fizesses algumas melhorias:

* Em várias das instruções, quando dizes que não podes converter uma coisa noutra deves ser mais concreto. Por exemplo, "pois uma instância de `Animal` pode não ser uma instância de `Dog`.
* Na 7ª instrução, penso que "vêm" não tem acento circunflexo.

2019-05-11 20:01 UTC, nunofachada requested changes
Inácio, atenção aos detalhes:

* No `Cat cat = new Dog();` não é _"não pode ser"_. É _"não é"_, simplesmente.
* Nas outras duas, a justificação está errada. Lê melhor e com mais atenção o meu comentário anterior.
* Não corrigiste o "vêm".
* Variável tem acento no "a" e não no "e".

2019-05-11 20:21 UTC, FPTheFluffyPawed commented
Desculpe. Não li bem o comentário do professor.

2019-05-12 18:01 UTC, nunofachada requested changes
Olá Inácio, a solução ficou pior, o Português ficou bastante confuso, e acho que ainda não leste bem o meu primeiro comentário. Nomeadamente:

* Um classe não inicializa nem deixa de inicializar outra. Essas frases por si só não fazem muito sentido.
* Ao contrário do que dizes, `Animal` pode ser de facto uma instância de `Dog` ou `Cat`. No entanto **pode não ser**. Atenção ao Português.

2019-05-13 10:20 UTC, nunofachada requested changes
A resposta ficou pior. Lê com **atenção** os vários comentários que fiz.

2019-05-13 11:34 UTC, FPTheFluffyPawed commented
Professor, estive a ler e tentar a perceber, mas antes de mandar outra proposta, pôde só dizer se isto está bem dito?

No caso do `Animal animal = new Dog()`, é correto se eu disser o seguinte:
* Válida, pois, estamos a instanciar um objeto `Animal` com o nome de variável `animal`, para depois inicializar como um objeto tipo de `Dog`.

Eu não sei se estou a confundir instanciar com inicializar, mas estou a ter problemas em perceber o que o professor quer que eu trate na minha solução.

2019-05-14 08:40 UTC, FPTheFluffyPawed commented
Eu fiz `push`, porque não sei se o professor foi notificado do meu comentário. É só para esclarecer a minha pergunta.

2019-05-14 18:30 UTC, fakenmc commented
Olá Inácio, desculpa pela demora. Eu vi logo a tua pergunta. Essa forma de descrever as coisas não está correta. Vou olhar de novo para a tua solução e tentar ser mais claro naquilo que pretendo.

2019-05-14 18:39 UTC, nunofachada requested changes
Comentários e alterações necessárias:

* A imagem não está a aparecer bem na tua resposta, como podes ver [aqui](https://github.com/VideojogosLusofona/lp1_exercicios/blob/4903ff8faaee49d896e7b8f3ebf80018264f3956/solucoes/04_uml/02.md). Para aparecer bem, o _link_ para a imagem (aqui na resposta) tem de estar dois níveis de pastas abaixo (ou seja, `../../img/uml02.png`).
* `Animal animal = new Dog();` - Não estás a instanciar (criar) um objeto do tipo `Animal`. Estás a fazer `new` de quê? A classe da qual crias uma instância é a que fazes `new`. A variável a ser inicializada neste caso é a variável `animal`, e é inicializada com uma instância de `Dog` (que foi aquilo que foi criado). Independentemente disso tudo, o ponto crítico aqui é dizeres que a instrução é válida pois `Dog` é um `Animal`, logo podes guardar uma instância de `Dog` numa variável do tipo `Animal`.
* `Cat cat = new Dog();` - O importante aqui é realçares que um `Dog` não é um `Cat`, logo não podes guardar uma instância de `Dog` numa variável do tipo `Cat`.

Não te vou dizer todas, senão estou na prática a escrever a resposta. Lê bem o que eu escrevi agora e volta a ler os meus comentários anteriores relativamente a cada uma das respostas que deste.

2019-05-15 13:09 UTC, FPTheFluffyPawed commented
Desculpe pela demora, obrigado pela clarificação. A próxima resposta que mandar vai ser a definitiva!

2019-05-16 13:30 UTC, nunofachada requested changes
* `Animal animal = new Dog();`
  * O que significa "Pos"?
  * "estamos a criar uma variável de tipo Animal para instanciar um objeto tipo Dog" - esta frase não faz sentido (uma variável não instancia objetos!) e pode simplesmente ser removida da explicação. A frase seguinte é mais do que suficiente para justificar a validade da instrução.
* `Cat cat = new Dog();`
  * Como te disse no ponto anterior, uma variável não instancia objetos. Esse tipo de frases simplesmente não faz sentido. A frase seguinte chega perfeitamente para justificar a resposta.
* `Cat cat = new Animal();`
  * Explicação demasiado complexa e não vai ao cerne da questão que é a seguinte: não podes guardar uma instância de `Animal` numa variável do tipo `Cat`, pois um `Animal` **pode não ser** um `Cat` (pode também ser, mas **pode não ser**).
* `a.Bark(); // 'a' é uma instância de Animal`: **OK**
* `dog.Eat(); // 'dog' é uma instância de Dog`: **OK**
* `float y = tareco.energy; // 'tareco' é uma instância de Cat`
  * A resposta está correta, mas `energy` não é do tipo `protected`, mas sim do tipo `float`. É de facto uma variável com visibilidade (ou acessibilidade) `protected` (e não **Protected**), mas o tipo da variável é `float`.
  * Foges um pouco à questão: é impossível aceder através de uma instância de `Cat` porquê? De onde é que `energy` pode ser acedida? Esse é que é o cerne da questão.
* `Console.WriteLine(myCat.Name); // 'myCat' é uma instância de Cat`
  * "Válida" e "É possível" são sinónimos neste caso, para quê repetires-te?
  * `Name` (com maiúscula) não é uma variável... atenção aos pormenores.
* `bobi.energy = 123.4f; // 'bobi' é uma instância de 'Dog'`
  * Mesma coisa que disse duas respostas atrás.
* `Dog pluto = new Animal();`
  * Tens de corrigir em conformidade com a instrução `Cat cat = new Animal();`, pois de facto, como dizes e bem, é o mesmo caso.
* `y.Meow(); // 'y' é uma instância de Cat`: **OK**
* `beast.Bite(); // 'beast' é uma instância de Animal`: **OK**
* `zz.Eat(); // 'zz' é uma instância de Cat`: **OK**

2019-05-19 11:23 UTC, FPTheFluffyPawed commented
Desculpe pela demora com a solução.

2019-05-19 18:16 UTC, fakenmc commented
Só faltam pequenos ajustes:

* `Animal animal = new Dog();` - Remove o "Pois, " e capitaliza o "isto". O pois não acrescenta nada e a frase fica esquisita.
* `float y = tareco.energy;` - Esta instrução é, como bem dizes, inválida. No entanto:
  * A justificação está incorreta. Pensa o que significa a visibilidade `protected`, e lembra-te que, como diz no enunciado, "Considera-se que todas as instruções ocorrem fora das classes presentes no diagrama".
  * Uma vez que se trata de uma _keyword_ de código, apresenta-a como tal: `protected` (e não **Protected**).
* `bobi.energy = 123.4f;` - Mesmo problema que o caso anterior.
* Por último, nos casos em que as instruções são válidas, uma das razões para essa validade é que o membro que está a ser acedido é `public`, pelo que podes adicionar esse facto. Se um membro tiver visibilidade `protected` ou `private`, não podes aceder a esse membro fora da classe (que é a situação indicada no enunciado).

2019-05-19 18:45 UTC, nunofachada requested changes
Detalhes em falta:

* Nas partes em que dizes "que é `public`" parece que te estás a referir à classe. Clarifica o Português de modo a que se perceba ao que te referes.
* Em Markdown código escreve-se entre plicas, logo deve ser \`protected\` e não \*\*protected\*\*.
* Nas respostas da variável `energy`: "das classes próprias"? Não será antes "das próprias classes"?

2019-05-19 18:55 UTC, fakenmc commented
Obrigado Inácio, solução aceite!

2019-05-19 18:55 UTC, merged