1ª proposta de solução
VideojogosLusofona/lp1_exercicios pull request #129
Opened 2019-05-12 15:24 UTC by FPTheFluffyPawed

Eu não tenha exatamente a certeza sobre a) com a propriedade de leitura, não sabia se era para usar `readonly` ou simplesmente utilizar só um `getter` privado. O professor pode clarificar se há diferença entre um `getter` privado e um `readonly`?

2019-05-12 18:55 UTC, nunofachada requested changes
Inácio, são necessárias alterações:

* Na alínea a) é dito para escreveres uma linha de código, não duas.
* A alínea b) está quase OK, excepto pelo facto de que as propriedades são normalmente públicas, de modo a serem acessíveis fora da classe (e tu meteste a propriedade como `private`). Além disso "tornasse" não me parece bem escrito, e a propriedade é só de leitura **dentro** e **fora** da classe.

Respondendo à tua questão, para uma propriedade ser só de leitura, basta ter o `get`, mas não o `set`, tal como fizeste, e bem. A _keyword_ `readonly` aplica-se a variáveis de instância ou de classe, tornando-as só de leitura. A _keyword_ `readonly` não se aplica em propriedades, pois nestas basta omitir o `set` para serem só de leitura.

2019-05-13 10:17 UTC, fakenmc commented
Olá Inácio, diz-me, faz sentido teres uma propriedade pública só de leitura com um `get` privado? Pensa no seguinte:

* Se a ideia é a propriedade ser só visível dentro da classe, então não faria mais sentido a visibilidade privada ser definida ao nível da propriedade (e não ao nível do `get`)?
* Se a ideia é a propriedade ser acessível fora da classe, porque vais meter o `get` privado? 
* Se só tens um `get` (e não um `set`) porque é que dás uma visibilidade ao nível da propriedade e outra oposta para o seu `get`?

Mais, o Visual Studio nem te deixa fazer isso. Experimenta.

2019-05-13 11:09 UTC, FPTheFluffyPawed commented
Desculpe, mandei a solução ontem e esqueci-me de verificar no Visual Studio se estava correto, demais disso, eu pensava que fiz commit sem o `private get`, que fiz só para experimentar. Ademais, obrigado por esclarecer a minha dúvida de antes sobre o `readonly`.

2019-05-13 20:47 UTC, merged

2019-05-13 20:47 UTC, fakenmc commented
Obrigado Inácio, solução aceite.