Resolvido exercício 1
VideojogosLusofona/lp1_exercicios pull request #13
Opened 2019-03-19 16:34 UTC by FPTheFluffyPawed

A minha proposta para o exercício 1.

2019-03-19 16:41 UTC, nunofachada requested changes
Olá Inácio,

* São executados mais comandos do que simplesmente o `git init`, uma vez que é feito pelo menos um _commit_. Logo são necessariamente mais comandos.
* Cada linha do texto da solução não deve ter mais de 80 colunas. Uma nova linha em Markdown não se reflete em nova linha na prática (é preciso ter uma linha de intervalo).
* Os comandos devem estar entre o caráter \`, por exemplo \`git init\`, e não entre o caráter '.

2019-03-19 16:46 UTC, FPTheFluffyPawed commented
Ah, obrigado pela ajuda professor, ainda não estava a perceber como fazer as colaborações. Vou corrigir o meu branch e tentar de novo.

2019-03-19 16:48 UTC, fakenmc commented
Sim, basta corrigires a solução, fazeres `add` do ficheiro da solução, `commit` e `push`, que a versão corrigida aparece-me imediatamente. Não é preciso fazeres _pull request_ de novo, pois este _pull request_ mantém-se aberto.

2019-03-19 22:49 UTC, nunofachada requested changes
Olá Inácio, está melhor, mas ainda não está 100%. Sugestões de melhoria:

* Repara como fica a [formatação que usaste](https://github.com/VideojogosLusofona/lp1_exercicios/blob/f2215046c4af32eb40218c79077df859fd35c698/solucoes/01_git/01.md). A sequência de comandos deve estar dentro de um bloco de código que termina e começa com três plicas \`\`\`. Além disso, para conseguires obter uma nova linha em Markdown tens de deixar uma linha em branco.
* Falta a mensagem de _commit_ após a opção `-m`.
* O que é um "comando executado em Git"?
* Alguns erros de Português, relê tudo antes de fazeres novo _commit_.

2019-03-20 11:18 UTC, nunofachada requested changes
Olá Inácio, a resposta está essencialmente correta, peço-te apenas que a voltes a ler e corrijas os erros de Português, pontuação, etc.

2019-03-20 14:03 UTC, merged

2019-03-20 14:03 UTC, fakenmc commented
Obrigado Inácio, solução aceite.