attempted solve for poo_19
VideojogosLusofona/lp1_exercicios pull request #133
Opened 2019-05-13 21:23 UTC by RafaelCS-Aula

2019-05-14 22:04 UTC, nunofachada requested changes
Rafael, são necessárias algumas correções:

* O valor `null` não é um tipo. Exemplos de algo que seja um tipo: `int`, `Console`, `Random`, `string`, `object`, `Convert`, `Vector3`, `MonoBehaviour`, etc.
* O que descreves sobre a _NullException_ não é bem assim, e de qualquer das formas não é relevante para responderes à questão.
* As _structs_ nem sempre são guardadas na _stack_.

Resumindo, tens que pensar melhor na resposta e dar-lhe uma volta completa.

2019-05-19 01:16 UTC, nunofachada requested changes
* Tenta começar as frases com uma palavra em Português e começada com maiúscula.
* A segunda frase está confusa. Tenta lá melhora-la um bocadinho. Por exemplo, falas no "programa" - mas que programa? Simplifica e clarifica.

2019-05-22 21:31 UTC, RafaelCS-Aula commented
Desculpe o intervalo entre soluções.

2019-05-22 21:37 UTC, merged

2019-05-22 21:37 UTC, fakenmc commented
Obrigado Rafael, solução aceite.