Resolução Ex31 03Poo
VideojogosLusofona/lp1_exercicios pull request #135
Opened 2019-05-18 14:52 UTC by RodrigoPrinheiro

Primeira tentativa no exercício 31 de Programação Orientada a Objetos

2019-05-19 01:04 UTC, nunofachada requested changes
Olá Rodrigo, são necessário algumas alterações:

* Podes colocar apenas solução 1 e separar as respostas por alíneas.
* Nas várias respostas coloca apenas aquilo que é pedido, ou seja, não ponhas _namespaces_ nem repetições da classe toda (por exemplo na questão 2) basta pores o método `ToString()`.
* Questão 1 - Esqueceste-te de considerar a parte "se a _tag_ for `null`".
* Questão 2 - Os dígitos significativos não estão bem definidos.
* Questão 3 - Não compliques, coloca apenas a instrução. Além disso na pergunta está dito que o nome da variável é `armourPack`, pelo que não precisas de criar um novo nome.
* Questão 4:
  * Revê o Português das várias respostas, tens alguns erros. Usa um corretor e verifica a construção das frases.
  * Palavras em inglês devem aparecer em itálico (e.g. _keyword_).
  * Na instrução 6 a justificação podia ser mais clara. Até podias justificar de outra forma, como fizeste na instrução 2, por exemplo.
  * Na instrução 7 a justificação está incorreta. Olha bem para o código e diz-me porque não funciona. Vê também o que digo no último ponto.
  * Na instrução 9 não estás a instanciar uma `Trap` como um `GameObject`. Esta justificação pode ser melhorada. Mesma coisa para a instrução 10.
  * Na instrução 11 acho que me enganei. A instrução é válida, vai ser impresso o `ToString()` de `Priority`, que é um objeto do tipo `Delegate` (é uma classe especial que define métodos). Isto é algo que só vamos dar em LP2. Vou corrigir o enunciado de modo a ter lá os parêntesis. Considera que esta instrução tem lá os parêntesis. Na instrução 7 passa-se algo semelhante, mas nesse caso a instrução é inválida pois não podes guardar algo do tipo `Delegate` num `int`. Na justificação dessa instrução não refiras nada sobre _delegates_ para não confundires os teus colegas, diz simplesmente que não podes guardar um método num `int`.

2019-05-20 14:34 UTC, fakenmc commented
* Questão 2 - A resposta está correta, mas falta a formatação para aparecer como código.
* Questão 4:
  * Instrução 5: Referes que poderíamos usar a _keyword_ `as`, no entanto um `GameObject` pode não ser uma `Trap` e a coisa ia correr mal (pois a conversão iria retornar `null` e irias tentar invocar um método em algo `null`, o que resultaria num `NullReferenceException`). Basta terminares após a frase "uma variável desse tipo" e a justificação é suficiente.
  * Instrução 7: Não estás a converter um tipo `void` pois não estás a chamar o método. Para isso precisavas de o chamar com os parêntesis. Estavas na prática a ir buscar a instância do método (do tal tipo `delegate`). Como não quero confundir a malta com isso nesta altura, diz simplesmente que não podes converter um método em `int`.
  * Instrução 8: Esta frase pode ser melhorada, sobretudo ali no final. Ficaria melhor "(...) qualquer propriedade`Tag`, uma vez que não implementa `ITaggable`".
  * Instruções 5, 9, 10: Não digas que uma classe "é uma extensão" de outra, diz que uma classe "estende" ou "deriva de" outra.
  * Instruções 9 e 10: A segunda parte da frase (a seguir ao "logo") está incorreta. Não estás a instanciar `GameObject` nenhum, nem poderias, pois `GameObject` é `abstract`. Tens de reformular esta justificação.
  * Instrução 11: Não tens de dizer o que está acontecer, tens de dizer a razão pela qual a instrução é válida ou não, e isso não dizes...

2019-05-21 12:42 UTC, nunofachada requested changes
* Coloca uma linha em branco entre "### Solução 1" e "Questão 1". Podes também realçar mais as diferentes questões, com cabeçalho nivel 4 (e.g. "#### Questão 1").
* Na questão 3, o código continua a aparecer sem formatação de código.
* Questão 4:
  * Falta linha em branco entre "Questão 4" e o início da tua resposta.
  * Instrução 5:
    * Falta vírgula a seguir antes de "não sendo possível".
    * Deveria ser "(...) chamar o método **a partir de uma** ou variável desse tipo".
  * Instrução 6: Não é impossível usar o construtor `GameObject()`. Apenas é impossível fazê-lo diretamente.

2019-05-22 07:52 UTC, RodrigoPrinheiro commented
Na questão 3 do meu lado aparece me com a formatação para código, não entendo qual é o problema para não estar a aparecer do lado do professor, mesmo a visualizar no git aparece corretamente.

2019-05-22 08:15 UTC, merged

2019-05-22 08:15 UTC, fakenmc commented
Obrigado Rodrigo, solução aceite.