Tentativa de solução do Ex 3 de POO
VideojogosLusofona/lp1_exercicios pull request #136
Opened 2019-05-18 16:13 UTC by King-Bugs

Tentativa de solução do Ex 3 de POO

2019-05-19 01:05 UTC, nunofachada requested changes
Olá Ricardo, a resposta está errada. Apesar de não ser `abstract`, não a podes instanciar. Falámos disto duas ou três aulas atrás. Olha bem para a assinatura da classe e vê lá o que te salta à vista.

2019-05-20 23:13 UTC, nunofachada requested changes
Olá Ricardo, a resposta está essencialmente correta, mas peço-te algumas melhorias ao nível da formatação e Português:

* Quando referes uma classe, método, variável, modificador de herança, modificador de visibilidade, etc, deves colocar entre plicas e não entre aspas. Por exemplo, se escreveres \`Math\`, a classe vai ficar formatada adequadamente como código, ou seja, `Math`. Outros exemplos: `public`, `abstract`, `boo`, `int`, `new`, etc.
* Relê e revê o Português, a construção de frases está fraquinha. Lembra-te que as respostas aceites ficam disponíveis para todos os teus colegas, pelo que devem estar o mais corretas possível.
* Quando quiseres colocar um bloco de código (como é o caso da assinatura da classe `Math`), podes formatar esse código especificamente para C#. Por exemplo, para obteres este resultado:

```cs
public static class Math;
```

Podes fazê-lo assim:

\`\`\`cs
public static class Math;
\`\`\`

* Ser `public` (ou não) não tem necessariamente relevância no facto de uma classe poder ser instanciada. Podes omitir essa parte da explicação.
* Atenção a esta frase: "não é possível criar variáveis da classe base". Dois apontamentos: 1) penso que queres dizer "criar instâncias"; 2) não digas "classe base", diz apenas "classe", pois a herança não é relevante para esta questão.
* Podes omitir **("Classe" "Nome de Objeto" = new "Método()")**, pois além de não estar inteiramente correto, traz um pouco de confusão.

2019-05-21 14:47 UTC, nunofachada requested changes
* Ricardo, para definir formatação de código deves usar plicas (\`), ou seja acentos graves, e não acentos agudos. Como podes ver [aqui](https://github.com/VideojogosLusofona/lp1_exercicios/blob/861446af107546ac52620296b76449da3f2811aa/solucoes/03_poo/03.md), a tua resposta não está bem formatada. Também sugiro que uses o Visual Studio Code (com as extensões indicadas no Moodle) para editares o Markdown das respostas fazendo uso do corretor ortográfico e do pré-visualizador de Markdown. Vai facilitar imenso.
* A expressão "é suposta" é bastante manhosa. Tenta arranjar uma forma melhor de dizer isso. No geral todo o Português do 1º parágrafo pode ser melhorado.
* O Português do 2º parágrafo também está bastante mais complicado do que precisa de ser. Podes dizer exatamente a mesma coisa usando pouco mais de metade das palavras que estás a usar.

2019-05-21 21:25 UTC, nunofachada requested changes
Muito melhor o Português agora. Só falta colocares as plicas (acentos graves) em vez de agudos nas várias palavras/código C# que referes ao longo do texto (classe `Math`, `abstract`, `static`).

2019-05-21 23:22 UTC, King-Bugs commented
Boa Noite Professor.
Não percebo o que está a acontecer.

Foi assim que eu fiz o _commit_ e o _push_: https://gyazo.com/465dcf82996cace1598679bfd09d9eea

No entanto, o documento que o professor recebeu está diferente e quando faço "git status", o git não deteta alterações nenhumas devido a ser o mesmo documento. Como devo proceder?

2019-05-22 07:58 UTC, fakenmc commented
Faz `git log` e diz-me o que aparece para o _commit_ mais recente por favor.

2019-05-22 18:29 UTC, King-Bugs commented
O _commit_ mais recente é:

```
commit 8f9cdb1d41d79ff4234116a9b6eea433ddf56297 (HEAD -> poo-ex3, origin/poo-ex3)
Author: Bugs <r1ch404ps@gmail.com>
Date:   Tue May 21 20:11:21 2019 +0100

    Tentativa de Submissão 4
```
Vou tentar editar o ficheiro, gravar, fazer _commit_, de seguida reverter o ficheiro novamente e fazer _push_ para ver se atualiza.

2019-05-22 18:33 UTC, fakenmc commented
Parece estar OK agora.

2019-05-22 18:36 UTC, merged

2019-05-22 18:36 UTC, fakenmc commented
Dei-lhe só um toque na formatação dos links e aceitei a solução. Obrigado.