Add solution to ex18 of poo
VideojogosLusofona/lp1_exercicios pull request #139
Opened 2019-05-20 15:32 UTC by PmaiWoW

2019-05-20 15:41 UTC, nunofachada requested changes
Pedro, são necessárias alterações:

* Linhas no máximo com 80 carateres.
* No enunciado copiado para o ficheiro da solução, tens de atualizar o _link_, que neste momento não funciona, como podes ver [aqui](https://github.com/VideojogosLusofona/lp1_exercicios/blob/42ca980ee5f3851d88345ee064529db21bb53e21/solucoes/03_poo/18.md). Pensa no seguinte: o ficheiro solução está na pasta `solucoes/03_poo`, mas o projeto está na pasta `problemas/03_poo/18`. Se tivesses de fazer `cd` de uma pasta para a outra diretamente, usando caminhos relativos, como farias? A resposta (excepto o `cd`) é igual o _link_ que tens de colocar.
* Por último e mais importante, a explicação está errada. Tens de pensar melhor no assunto. Dica: neste caso não existem cópias da _struct_ `MyStruct`.

2019-05-20 16:40 UTC, PmaiWoW commented
O novo push foi feito prematuramente por acidente

2019-05-20 16:53 UTC, fakenmc commented
Não tem problema. Vê o meu feedback do exercício anterior relativamente à questão dos 80 carateres.

2019-05-21 10:21 UTC, nunofachada requested changes
Olá Pedro, está melhor, mas aquela parte a seguir a "logo será possível" não me convence nada. Faz o desenho (para ti) do que se está a passar, e tenta explicar a situação a partir dai. Se achares que facilita até podes incluir o desenho na resposta, em modo Git LFS (apenas uma sugestão, e apenas se achares que facilita).

2019-05-21 12:00 UTC, PmaiWoW commented
Boa tarde stor, só para ter a certeza, a resposta está bem e o que deve ser alterado é a forma da explicação da resposta? Ou é a resposta em si que ainda não está totalmente correta?

2019-05-21 12:31 UTC, nunofachada requested changes
Olá Pedro, as minhas dúvidas são:

* "logo será possível alterar as suas variáveis de instância" -> Uma vez que a `struct` não é imutável é sempre possível alterar as suas variáveis de instância. Não vejo a relevância desta afirmação.
* A parte que não percebo mesmo é esta: "pois são referências para outros tipos de variáveis". Para mim isto não faz muito sentido.
* Resumindo, tudo o que vem a seguir ao "logo será possível" tem que ser reformulado. Eu diria mesmo, apaga a frase "logo será possível (...)", e reformula essa justificação.

2019-05-21 12:32 UTC, PmaiWoW commented
Ok stor, obrigado pelo esclarecimento

2019-05-22 11:10 UTC, nunofachada requested changes
Está melhor, mas a frase pode ser mais simplificada ainda. E atenção ao limite de 80 carateres por linha.

2019-05-22 12:51 UTC, nunofachada requested changes
Continuo a não ficar convencido com a resposta. Algumas sugestões:

* Mete um ponto final a seguir a "(tipo de referência)".
* Apaga o que vem a seguir.
* Até a esse ponto final constataste que a _struct_ encontra-se num _array_, que é um tipo de referência. Logo a _struct_ existe em que zona da memória? Logo... etc. A conclusão final tem de ir por este caminho.

2019-05-22 13:43 UTC, nunofachada requested changes
Está a ficar melhor, mas porque é que, ao estar na `heap`, a alteração da variável de valor (_struct_) se repercute de um método para outro?

PS - Atenção aos 80 carateres.

2019-05-22 14:22 UTC, fakenmc commented
Não está perfeito, mas também não está incorreto. Vou aceitar.

2019-05-22 14:22 UTC, merged