Solução exercicio 28 Git
VideojogosLusofona/lp1_exercicios pull request #155
Opened 2019-05-22 18:55 UTC by DianaNoia

2019-05-22 19:08 UTC, nunofachada requested changes
A resposta está incorreta. Relativamente ao comentário, neste caso podes remove-lo pois já estás a explicar antes o que o comando faz.

2019-05-23 14:33 UTC, fakenmc commented
Olá Diana, a resposta está incorreta. Nem sequer falamos do comando `git show-branch` nas aulas, penso eu.

2019-05-24 14:55 UTC, DianaNoia commented
Olá professor, eu fiquei confusa acerca deste exercício, se o comando não é 'git branch --vv' é 'git remote show origin"?
Já agora, estou com uma dúvida acerca da época especial. Se nós só tivermos negativa nos testes, quando formos fazer o recurso só fazemos uma parte teórica? Como é que isso funciona?

2019-05-25 08:53 UTC, fakenmc commented
Olá Diana, o comando não é exatamente `git branch --vv` mas anda lá muito perto. Se tentares correr dessa forma vai dar erro. Vê melhor nos slides.

Quanto ao resto respondo no Moodle.

2019-06-08 21:51 UTC, fakenmc commented
Olá Diana, esta resposta estava inicialmente correta, deve-me ter falhado alguma coisa na altura. A resposta é `git branch -vv`, como tinhas indicado da primeira vez. Corrigi e aceitei.

2019-06-08 21:51 UTC, merged