Add new solution to problem 25 of poo
VideojogosLusofona/lp1_exercicios pull request #172
Opened 2019-05-29 10:05 UTC by MizuRyujin

2019-05-29 12:59 UTC, nunofachada requested changes
* Qual a visibilidade da classes que implementaste?
* A `enum Direction`, sendo um tipo, até poderia estar num ficheiro próprio, ou não?
* O enunciado indica que a propriedade `Name` deve ser apenas de leitura, o que não é o caso.
* Na classe `NPC`, não é boa prática inicializares variáveis fora do construtor (ou fora do `Awake()`, se estivesses a usar Unity).
* Porque razão fazes `override` de `Name` se não alteras a sua funcionalidade?
* Porque razão inicializas `Name` nas subclasses se já o fazes na superclasse (uma vez que chamas o construtor da superclasse através de `base()`)?
* Na classe `NPC`, uma vez que a propriedade `Directions` é apenas usada dentro do método `Move()`, porque razão está definida ao nível da instância? Não podia ser uma variável local?
* Na classe `Player`,o método `Move()` tem um _bug_ grave. Se o utilizador se enganar, não estás a guardar o valor da nova escolha do utilizador, sendo sempre devolvida a primeira escolha errada. Além disso é má prática fazeres depender recursividade do _input_ do utilizador. O utilizador pode crashar-te o programa (_stack overflow_) se se enganar muitas vezes, propositadamente ou não.

2019-05-31 19:54 UTC, MizuRyujin commented
- Adicionada as visibilidades das classes;

- A `enum Directions` passa para o seu próprio ficheiro, onde a classe `Character` a utiliza;

- Retirados todos os overrides desnecessários e as inicializações do `Name` nas que estendem `Character`;

- Variável `rnd` inicializa no construtor;

- Faço por tentar retirar o bug, nos testes não aceita algo diferente do input pedido e se é diferente mostra mensagem de erro, passa `PChoice` para `null` e recomeça método `Move()`.

2019-06-01 18:09 UTC, nunofachada requested changes
* Classe `Character`:
  * Qual a sua visibilidade?
  * Variável de instância `Directions`:
    * Má prática ter variáveis de instância não _read-only_ públicas.
    * Variáveis de instância começam com minúscula.
    * Pior que tudo: esta variável não serve para nada, pois podes usar os valores de uma `enum` diretamente da `enum`.
  * No primeiro `case` tens um espaço "não solicitado" entre `(char)` e `Directions.North`. Podes resolver todos estes problemas de indentação com CTRL+K+D no Visual Studio.
  * Método `GetDirection()`: este método só parece ser útil para as classes derivadas. Sendo assim, a sua visibilidade poderia ser mais limitada.
* Classe `NPC`:
  * Porque teres uma propriedade `Direct` onde guardas a direção, se a direção é devolvida pelo método `Move()`? Estás a complicar desnecessariamente.
* Classe `Player`:
  * As propriedades `PChoice` e `Direct` não servem para nada. São apenas usadas dentro do método `Move()`, ou seja, poderiam perfeitamente ser variáveis locais desse método. Novamente, estás a complicar.
  * No método `Move()`:  
    * Porque razão fazes `ToUpper()` se apenas queres pedir números? Números em maiúscula?
    * Porque razão fazes um `if` para ver se a escolha é 1, 2, 3 ou 4, e depois um `switch` com exatamente a mesma pergunta? Não faz sentido.
    * Já referi no meu comentário anterior. Estás a fazer depender a recursividade do utilizador (isto é, o método `Move()` chamar-se a ele próprio). Isto é um _bug_ (e um autêntico buraco de segurança em qualquer software/jogo), pois permites que o utilizador te crashe o programa com um _stack overflow_. Estás novamente a complicar sem necessidade nenhuma.
* Classe `Program`:
  * Pedir nomes de NPC e jogador: tal não é pedido no enunciado. Podes deixar ficar, mas o facto é que estás a complicar novamente e a perder tempo importante para teres o exercício aceite.
  * Porque razão não guardas o `char` devolvido pelo método `Move()` numa variável local? Porquê teres propriedades extra que criaste propositadamente para esse efeito? Porquê dares uma volta tão grande quando caminho é sempre em frente?
* Em toda a solução: tens vários comentários em que não colocas um espaço entre o início do comentário `//` e o comentário propriamente dito. É boa prática teres lá o espacinho colocado.
* Uma coisa que tens de ter em conta é o seguinte: nunca compliques mais do que o necessário (princípio [KISS](https://en.wikipedia.org/wiki/KISS_principle)). A ideia com que fico desta tua resolução é que estás a tentar complicar sempre que possível. Uma boa programação é exatamente o contrário. Simplificar sempre que possível. Lê bem o que escrevi, lê bem o enunciado, e se for preciso, começa de novo.

2019-06-20 11:36 UTC, fakenmc commented
_Pull request_ fechado pois prazo para submissões e correções terminou ontem.

2019-06-20 11:36 UTC, closed without merging