Add solution to ex38 of poo
VideojogosLusofona/lp1_exercicios pull request #176
Opened 2019-06-02 15:12 UTC by PmaiWoW

2019-06-02 17:15 UTC, nunofachada requested changes
Olá Pedro, a resposta está incorreta e tem coisas não pedidas no enunciado (`ToString()`). Lê melhor o enunciado.

2019-06-02 17:43 UTC, nunofachada requested changes
Continua errado. Não tens acesso à variável de instância `textureFile` na classe derivada pois esta é privada. Mesmo que não fosse privada, é sempre boa prática ser a própria classe a definir o valor das suas variáveis/propriedades, e não classes derivadas. Estas últimas devem fazê-lo através da informação passada via o construtor da classe base.

2019-06-02 19:58 UTC, PmaiWoW commented
Então se a classe derivada tiver a sua própria string, de nome digamos _filename_, esta forma de fazer já seria correta?

2019-06-02 20:02 UTC, PmaiWoW commented
Algo digamos deste género:

```cs
private string filename;

public PNGTexture(string filename, string textureFile) : base(textureFile)
{
    filename = $"{textureFile}.png";
}
```

2019-06-03 15:09 UTC, fakenmc commented
Ainda incorreto. Lê atentamente o meu comentário anterior. Está lá a resposta.

2019-06-04 17:01 UTC, fakenmc commented
Bingo!

2019-06-04 17:01 UTC, merged