solução 04 ex 6
VideojogosLusofona/lp1_exercicios pull request #190
Opened 2019-06-05 17:43 UTC by FPTheFluffyPawed

Não tenho muito a certeza sobre esta solução, principalmente na relação entre as classes com a composição.

2019-06-09 18:52 UTC, nunofachada requested changes
Olá Inácio, são necessárias várias alterações:

* Limite de 80 carateres no enunciado.
* Falta linha em branco entre o nome de cada classe e o código que se segue.
* Ignoraste a visibilidade das classes. Repara que o diagrama UML também refere esta visibilidade. Também ignoraste a visibilidade em vários membros das classes ao longo da tua resolução.
* Os campos que aparecem com a primeira letra maiúscula não são variáveis de instância. A primeira letra é maiúscula por uma razão.
* Não estás a respeitar o modificador de herança de `Map`. Repara na fonte usada para o nome desta classe no diagrama.
* Na classe `Map` estás a instanciar coisas diretamente na sua declaração ao nível da classe. Estas instanciações são para ser feitas nos construtores das classes e não diretamente na declaração. No Unity farias estas instanciações no `Awake()`.
* Em todo o caso, estás a criar jogadores dentro de `Map` e a guarda-los em variáveis de instância, o que implicaria uma relação de composição entre `Map` e `Player`. No entanto a relação que lá aparece é de agregação.
* Nas classes derivadas de `Map` como é suposto inicializares os membros dessas classes? Esqueceste-te da visibilidade dos membros, mas o facto é que estes são privados por omissão. Estas classes não têm qualquer funcionalidade assim.
* A relação que apresentas entre `Map` e `Game` é uma mera dependência. No entanto o diagrama mostra a relação mais forte que existe: composição. Além disso o código não faz nada, pois `Game` simplesmente limita-se a criar `Map` e não faz mais nada.
* Não sei se testaste isto no Visual Studio, mas certamente haverão alguns _warnings_ referentes a coisas que digo aqui. Senão testaste no VS, testa.

2019-06-10 19:27 UTC, FPTheFluffyPawed commented
Professor, eu tenho uma dúvida sobre como fazer a agregação entre `Map` e `Player`. Se tenho que ter construtor para ter agregação, e a classe `Map` é `abstract`, como é que sou suposto ter uma composição entre `Map` e `Game` se eu não posso instanciar a classe?

O resto até agora penso que está bem feito, mas quero que o professor me ajude nesta parte.

2019-06-10 21:26 UTC, nunofachada requested changes
Continuam a ser necessárias alterações:

* Tens de copiar o enunciado como deve de ser. Por exemplo, não podes partir uma palavra ao meio em Markdown, senão ficas com um espaço. Usa o _previewer_ de Markdown do VS Code.
* Na classe `Player`, parece-te plausível que o ID e o nome do jogador possam mudar após o mesmo ser instanciado (sobretudo o ID)?
* Na classe `Map`:
  * `Name` não é uma variável de instância (e se fosse não seria certamente pública).
  * `Map` tem vários _players_, não apenas um. Uma vez que `Map` não pode criar e guardar os seus _players_ numa variável de instância (pois a relação não é de composição), os _players_ têm de ser criados noutro lado e passados posteriormente (ou na altura da instanciação) às instâncias de `Map`.
  * O método `PrintPlayerNames()` não recebe nenhum argumento. Aliás, o método não faz sentido tal como o apresentas, pois assumes que só há um _player_ mas aceitas que te digam (através do parâmetro) que há mais.
* Nas classes derivadas de `Map`:
  * Parece-te que aquelas propriedades específicas podem ser alteradas após os mapas serem instanciados?
  * As classes precisam de um construtor, tendo em conta o que digo no ponto anterior, mas também porque precisam de invocar o construtor da classe base (que por ser abstrata, não pode ser instanciada diretamente).
* Na classe `Game`:
  * Qual a visibilidade da variável de instância `map` e porque razão não inicializas o mapa num método? Já referi que instanciar coisas diretamente no corpo da classe (fora do construtor e métodos) não é boa prática, sobretudo se forem tipos de referência. Além disso, e se quisesses experimentar com diferentes tipos de mapa dentro do método `GameLoop()`?
  * Ainda na sequência do ponto anterior, não pode instanciar `Map`, pois é uma classe abstrata. No entanto, podes instanciar as classes derivadas e guarda-las numa variável do tipo `Map`.
  * O método `GameLoop()` é o principal método de teste deste mini-projeto. Nunca poderá ser tão pequeno.
* Por último, desenvolve o projeto no Visual Studio, pois tens vários erros que seriam realçados caso tivesses a fazer dessa forma.

2019-06-10 21:33 UTC, FPTheFluffyPawed commented
Obrigado pelos comentários, penso que já entendi isto!

2019-06-11 19:07 UTC, nunofachada requested changes
Olá Inácio, está melhor, mas ainda não está perfeito:

* O diagrama UML refere que um mapa pode ter um ou mais jogadores. Não refere que são três jogadores. Ou seja, tem que ter uma coleção de jogadores.
* Em todo o caso, na classe `Map`, as tuas variáveis de instância do tipo `Player` são públicas. Má prática.
* Nas classes derivadas de `Map` estás a guardar o nome e o _filename_ do mapa. Não precisas, pois isso já é feito pelo construtor de `Map`, que já estás a invocar a partir das classes derivadas.
* Estás a criar os jogadores nas classes derivadas, o que na prática implica que tens uma composição entre `Map` e derivadas e `Player`. Não é isso que está no UML, como já referi. Pensa da seguinte forma: quem é que cria as instâncias específicas de `Map`? Não será também sua responsabilidade criar os jogadores e passa-los a essas instâncias específicas de `Map`?
* A classe `Game` tem um mapa, não dois. Pensa assim: tem uma variável de instância do tipo `Map`, mas essa variável pode ter diferentes mapas ao longo da sua vida.
* Se criaste dois mapas porque é que só tens um jogo jogado? Não seria mais claro do ponto de vista do código, incrementares o número de jogos jogados cada vez que crias um mapa?

2019-06-12 11:11 UTC, nunofachada requested changes
* Num `Map`, fará sentido o nome do mapa e o nome ser modificável após a instanciação?
* Os jogadores continuam a ser instanciados na classe `Map`, logo continuas a ter composição e não agregação, que é o que está no diagrama UML. Dica: apesar de não existir relação entre `Game` e `Player`, podes assumir dependência, que por vezes omite-se dos diagramas.
* O _game loop_ ficou muito melhor. No entanto tens algum código repetido quando crias um tipo de mapa ou outro. Não consegues evitar essa repetição?
* Era fixe mostrares o números de jogos jogados no `Main()`, após invocares o _game loop_.

2019-06-12 16:37 UTC, FPTheFluffyPawed commented
Eu estava a tentar evitar essa relação entre `Game` e `Player`, por isso é que fiz o método. Penso que agora ficou melhor. Continua a ser agregação com a lista de `Player` privado no `Map`, certo? Só era composição por causa de criar um `Player` no método antigo como tinha?

2019-06-12 23:14 UTC, fakenmc commented
Olá Inácio, está bom agora. Sim, agora como tens é agregação, pois os _players_ estão numa variável de instância de `Map`, mas são criados externamente ao `Map`.
Só falta fazeres _merge_ da tua solução com a solução existente para poder aceitar.

2019-06-12 23:30 UTC, FPTheFluffyPawed commented
Oops, acho que fiz mal com este merge conflict, agarrou o meu master e meteu todo no branch...

2019-06-13 15:56 UTC, fakenmc commented
Inácio, o _merge_ foi bem feito. Solução aceite.

2019-06-13 15:56 UTC, merged