Solução exercicio 77 Poo
VideojogosLusofona/lp1_exercicios pull request #212
Opened 2019-06-14 17:02 UTC by DianaNoia

2019-06-14 22:00 UTC, nunofachada requested changes
Olá Diana, no ponto 3 nem todas as respostas estão corretas. Verifica com mais atenção as tuas respostas. Entre outras coisas, analisa o tipo de cada variável e se estás a passar o tipo correto na chamada ao método.

2019-06-15 15:29 UTC, nunofachada requested changes
Na resposta 3:

* Na tua segunda resposta (quarto método apresentado na pergunta): os valores de `y` (e também de `z`, se vires com atenção) não estão corretos.
* Na tua terceira resposta (quinto método apresentado na pergunta): verifica bem os tipos passados com os tipos que o método deve receber.
* Na tua última resposta, sê mais explícita no valores que `z` assume. Não te esqueças que se trata de um _array_ de `double`.

2019-06-15 19:40 UTC, nunofachada requested changes
Ficou pior agora. Tens que ver a parte 3 deste exercício com mais atenção. Se for preciso experimenta em Visual Studio, vendo o que funciona e fazendo `WriteLines()` quando funcionar.

2019-06-15 23:54 UTC, DianaNoia commented
Olá prof, quando vou testar as várias instruções o params double[] z mostra sempre System.Double[] na parte do array, não sei como corrigir.

2019-06-16 00:26 UTC, fakenmc commented
Quando imprimes um _array_ diretamente é isso que é suposto aparecer. O que tu queres é imprimir os elementos do _array_, um a um, e tu sabes fazer isso.

2019-06-16 11:32 UTC, nunofachada requested changes
Olá Diana, a resposta agora está essencialmente correta, mas peço-te que melhores o seguinte aspeto. O _array_ `z` contém `doubles`, mas na tua resposta apresentas os seus conteúdos por vezes como 
`floats`, por vezes como `ints`. Possivelmente até foram valores desses tipos que foram passados para o _array_, mas como o _array_ é de `doubles`, os valores são implicitamente convertidos para `double`. Sê mais clara.

2019-06-16 14:17 UTC, fakenmc commented
Obrigado Diana, solução aceite.

2019-06-16 14:17 UTC, merged