83 POO
VideojogosLusofona/lp1_exercicios pull request #216
Opened 2019-06-15 13:32 UTC by DianaNoia

Olá professor,
Estou com uma dúvida no ponto 3. Quando diz "à parte de manipular o npc diretamente no array", quer dizer que é para alterar o valor do Hp do npc sem alterar esta parte? : {new NPC(12.5f), new NPC(19.5f)};

2019-06-15 15:19 UTC, nunofachada requested changes
* _array_ em itálico (palavra em Inglês).
* Sim, não podes mudar o HP inicial. A solução passa por obteres uma referência para o NPC em questão, apesar de `NPC` agora ser um tipo de valor. É matéria da última aula, embora possas ter que pesquisar um pouco sobre como fazer isso tendo um _array_ com tipos de valor.

2019-06-16 11:27 UTC, fakenmc commented
Olá Diana, infelizmente a resposta 3 ainda está incorreta. Lê melhor o meu comentário anterior. Atenção também à indentação.

2019-06-16 12:06 UTC, DianaNoia commented
Olá prof, 
Peço desculpa, tinha-me esquecido de meter o ref na resposta. 
Penso que agora está correto.

2019-06-16 14:14 UTC, nunofachada requested changes
Olá Diana, detalhes ainda em falta:

* Resposta 1:
  * Por vezes aparece a palavra _array_ sem estar em itálico.
  * "Depois é dada a primeira posição do array ao NPC1" - esta frase precisa de ser melhorada. O que "dado" efetivamente? O que é isso de NPC1? Na mesma frase tens uns espaços a mais antes do ponto final.
  * `foreach` não é uma função, pelo que podes apresentar a palavra sem os parêntesis.
* Resposta 2:
  * Quando te referes a classe ou `struct` `NPC` explicitamente, a palavra NPC deve aparecer em formatação de código. Não é preciso se estiveres a falar de NPCs de uma forma mais geral, sem ser explicitamente uma classe/struct, como aliás fazes a resposta 1.
  * No último parágrafo desta resposta acho que podes melhorar um pouco o Português.
* Resposta 3:
  * Atenção à indentação.
  * No geral acho que podes melhorar a última frase, tanto ao nível de Português, como dos termos técnicos usados.

2019-06-17 18:40 UTC, DianaNoia commented
Olá prof, eu fiz merge da minha solução com a do pedro, esqueci-me de esperar pela sua resposta.

2019-06-18 08:31 UTC, nunofachada requested changes
* Quando referes NPC1, estás a referir-te à instância de NPC guardada na variável `npc1`? Clarifica isso.
* Quando referes `struct` podes usar formatação de código.
* "Mudanças na cópia não afeta**m** o original"
* Atenção à indentação na resposta 3.
* Na última frase, "uma instância da referência guardada" não está correto. Clarifica.

2019-06-18 12:53 UTC, nunofachada requested changes
* "(...) que é guardada na variável `npc1` **e** no primeiro índice (...)"
* Tens um "1." na resposta 2.
* Na resposta 3, a indentação continua incorreta.
* A última frase está melhor, mas ainda tem este problema: "no índice indicado da
variável `npc1`.". Acontece que a variável `npc1` não é um _array_, logo não tem um índice. Esta parte do índice tem que ser referida relativamente ao _array_.

2019-06-18 14:57 UTC, fakenmc commented
Obrigado Diana, solução aceite.

2019-06-18 14:57 UTC, merged