Add solution to ex86 of poo
VideojogosLusofona/lp1_exercicios pull request #228
Opened 2019-06-16 23:35 UTC by PmaiWoW

2019-06-17 10:41 UTC, nunofachada requested changes
* O enunciado não pede `Console.WriteLine()` dentro do método `Saturate()`. Os valores devem vir todos inicializados de fora.
* Nada te garante que o 1º `int` seja positivo. Tens duas formas de garantir isso, usa uma delas.
* Não estás a responder à pergunta feita no fim do enunciado.

2019-06-17 20:46 UTC, nunofachada requested changes
* Como referi, o valor `y` tem de vir inicializado de fora, ou seja, não podes ter um `Console.ReadLine()` dentro do método. Se quisesses usar este método no Unity não poderias ter `ReadLines()` certo?
* Prefiro que obrigues o código cliente a passar um inteiro positivo (sem sinal) `x`, ao contrário da solução que estás a usar.
* A tua justificação final está incompleta/não é a melhor, e tem um erro de Português.

2019-06-18 12:44 UTC, nunofachada requested changes
O teu método `Saturate()` não vai funcionar no Unity com `Console.WriteLines()`. Lê com atenção os meus comentários anteriores.

2019-06-18 15:01 UTC, nunofachada requested changes
* Continuas a não garantir que o utilizador passe um **inteiro sem sinal** no 1º parâmetro.

2019-06-19 09:43 UTC, PmaiWoW commented
Tive que fazer o merge e reescrever partes do enunciado pois vieram de novo codificadas mal no ficheiro md da solução já no repositório

2019-06-19 10:57 UTC, fakenmc commented
Volto a dizer:

* Continuas a não garantir que o utilizador passe um **inteiro sem sinal** no 1º parâmetro.

2019-06-19 11:02 UTC, PmaiWoW commented
Não pode ser feito com ao usar o método Math.Abs no input do jogador?
Eu tentei com o código atual e funcionou, mas estou na dúvida de como fazer se não for desta forma

2019-06-19 11:05 UTC, fakenmc commented
Pode, foi como o teu colega fez. E tu tinhas feito um `Abs()` manualmente senão me engano (tipo `if (x < 0) then x = -x`). No entanto, o que eu quero na tua resposta é que o utilizador ou código cliente só consiga passar como primeiro parâmetro **inteiros sem sinal**.

2019-06-19 11:07 UTC, PmaiWoW commented
Ok acho que já percebi, demorou-me um bom bocado...

2019-06-19 11:19 UTC, nunofachada requested changes
Pedro, acho que fizeste asneira. Mudaste a solução do teu colega. Forma mais fácil de resolver a situação: copia Markdown original do enunciado/solução já aceite e trabalha em cima disso.

2019-06-19 11:33 UTC, PmaiWoW commented
ah, ok vou reverter as mudanças, foi por engano

2019-06-19 15:11 UTC, nunofachada requested changes
* No `Main()` estás a fazer 3x a mesma coisa. Há formas melhores de fazer isso sem ser repetir o código.
* No método `Saturate()`, é mesmo preciso usares a classe `Convert` para converteres um `uint` num `int`?

2019-06-19 17:47 UTC, PmaiWoW commented
Posso fazer um cast neste caso ou seria preferível outra forma?

2019-06-19 18:13 UTC, fakenmc commented
Experimenta.

2019-06-19 18:28 UTC, nunofachada requested changes
Está óptimo, só falta uma pequena coisa para o programa compilar.

2019-06-19 18:34 UTC, merged

2019-06-19 18:34 UTC, fakenmc commented
Óptimo, foi duro mas o 2 é teu.

2019-06-19 18:42 UTC, PmaiWoW commented
Obrigado stor, ainda planeio em fazer alguns exercícios para estudar para o teste, se quiser feedback posso enviar para aqui mas não são aceites ou posso enviar por moodle ou algo assim?

2019-06-19 18:43 UTC, fakenmc commented
Sim, podes enviar, eu se conseguir dou feedback.

2019-06-19 18:46 UTC, PmaiWoW commented
Ok, obrigado stor.