ex78_first try
VideojogosLusofona/lp1_exercicios pull request #235
Opened 2019-06-18 16:48 UTC by RodrigoMarques23

2019-06-18 18:06 UTC, nunofachada requested changes
Rodrigo, são necessárias as seguintes alterações:

* Falta uma linha em branco entre "### Solução 1" e o início da solução propriamente dita.
* Tens vários erros de Português. Relê o texto e corrige por favor.
* Existem mais vantagens e desvantagens, creio eu.
* Não estás a usar formatação Markdown nenhuma. Podias usá-la para evidenciar "Vantagens..." e "Desvantagens...", ou para listar os itens que apresentas tanto nas vantagens como nas desvantagens.

2019-06-18 20:00 UTC, RodrigoMarques23 commented
Honestamente não vejo o que possa ser(?). O código corre sem erros e sem avisos...

2019-06-18 21:32 UTC, nunofachada requested changes
A solução está correta, essa formatação Markdown é que nem por isso. [Vê como fica](https://github.com/VideojogosLusofona/lp1_exercicios/blob/bd02512f7d375e4888525e1c8f48312f2d1b1243/solucoes/03_poo/78.md). Estás a usar o Visual Studio Code com o preview de Markdown para pré-visualizares como ficam as soluções?

2019-06-18 21:54 UTC, RodrigoMarques23 commented
Não, o professor quando diz que a formatação não está correta, é devido as caixas cinzentas por detrás das vantagens/desvantagens?

2019-06-18 22:22 UTC, RodrigoMarques23 commented
Outra questão, o professor vai colocar mais exercícios ainda?

2019-06-18 22:49 UTC, fakenmc commented
* Sim, mas não só. Dá uma vista de olhos nas soluções dos teus colegas (aquelas que contêm mais texto), e [tens aqui](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) uma referência rápida de Markdown.
* Não vou colocar mais exercícios, o deadline é amanhã ao meio dia e ainda existem muitos exercícios por resolver.

2019-06-20 11:37 UTC, fakenmc commented
_Pull request_ fechado pois prazo para submissões e correções terminou ontem.

2019-06-20 11:37 UTC, closed without merging