ex54_1ºtry
VideojogosLusofona/lp1_exercicios pull request #238
Opened 2019-06-19 01:41 UTC by RodrigoMarques23

2019-06-19 01:42 UTC, RodrigoMarques23 commented
-Ignore o nome do commit, apenas agora reparei que tinha escrito ex55...

2019-06-19 10:46 UTC, nunofachada requested changes
* Enunciado novamente mal copiado: este problema é o 54 (e não 55), e a variável `x` não aparece com formatação de código. Como já referi, tens de copiar sempre o Markdown original dos enunciados.
* A resposta começa bem, depois vai por ali abaixo. Existe de facto maneira de métodos poderem alterar variáveis de tipos de valor, mas demos isso na última aula e neste código não vejo lá nada disso.

2019-06-19 16:24 UTC, RodrigoMarques23 commented
Correto mas neste caso, como é que posso saber se o valor de x é alterado? Não tenho qualquer tipo de informação sobre a instância AddOne()

2019-06-19 18:22 UTC, fakenmc commented
Tens pelo menos a informação que o valor passado a `AddOne()` não é `out` nem `ref`, pois é preciso indicar isso nos parâmetros em questão quando se invoca o método.

2019-06-20 11:38 UTC, fakenmc commented
_Pull request_ fechado pois prazo para submissões e correções terminou ontem.

2019-06-20 11:38 UTC, closed without merging