ex48_1ºtry
VideojogosLusofona/lp1_exercicios pull request #239
Opened 2019-06-19 02:00 UTC by RodrigoMarques23

2019-06-19 10:49 UTC, nunofachada requested changes
* Enunciado mal copiado novamente.
* Formatação Markdown da resposta está incorreta.
* Resposta com erros de Português.
* A resposta em si está errada. Nota que este é um exercício de recursividade. Se procurares no Google por GCD ficas logo com uma ideia melhor daquilo que o método faz.

2019-06-19 16:48 UTC, RodrigoMarques23 commented
Foi a primeira coisa que pesquisei, no entanto não entendi que valor é passado ao método GDC()

2019-06-19 18:23 UTC, fakenmc commented
Os valores que são passados ao método `GCD()` são os que lá estão. Não sei o que te posso dizer mais além disso.

2019-06-20 11:38 UTC, fakenmc commented
_Pull request_ fechado pois prazo para submissões e correções terminou ontem.

2019-06-20 11:38 UTC, closed without merging