solução para alinea 3
VideojogosLusofona/lp1_exercicios pull request #242
Opened 2019-06-19 11:00 UTC by FPTheFluffyPawed

2019-06-19 11:03 UTC, fakenmc commented
Olá Inácio, estás quase lá, mas não é bem o _abstract factory pattern_.

2019-06-19 11:07 UTC, FPTheFluffyPawed commented
Eu não tenho a certeza sobre a diferença entre _Abstract Factory pattern_ ou só _Factory Pattern_. O professor quer dizer que é o _Factory Pattern_? Sendo que, pôr o que estou a ver, o _Factory Pattern_ realmente não têm construtores enquanto o _Abstract Factory pattern_ utiliza alguns?

2019-06-19 11:08 UTC, fakenmc commented
Não existe um _factory pattern_, existem vários. Um deles é o _abstract factory_, que não é este.

2019-06-19 11:35 UTC, FPTheFluffyPawed commented
Estive a procura, e de o que vejo e encontro, só consigo relacionar o _Factory Method_ ao programa que está no exercício.

2019-06-19 15:09 UTC, fakenmc commented
Se só consegues relacionar o _Factory method pattern_ com o que está no exercício, então se calhar é porque estás correto.

O _Factory method pattern_ é apenas um dos vários _factory patterns_.

2019-06-19 15:29 UTC, FPTheFluffyPawed commented
Ah, já entendi o meu erro. Oops.

2019-06-19 15:52 UTC, nunofachada requested changes
Ok, portanto é de facto o _factory method_, mas a explicação não está muito correta. Uma pequena pesquisa no Google sobre este _pattern_ permite-te arranjar uma descrição melhor. Não te esqueças depois de referir a fonte.

Depois se quiseres aproveita e tenta resolver o resto do exercício, até às 21h.

2019-06-19 16:11 UTC, FPTheFluffyPawed commented
Ah, também uma pergunta, tenho que fazer um novo _pull request_ para cada alínea ou posso fazer _push_ com as soluções para cada alínea?

2019-06-19 16:22 UTC, fakenmc commented
Podes continuar neste.

2019-06-19 18:12 UTC, nunofachada requested changes
* Resposta 1:
  * Apenas é pedido para criares um método e não dois.
  * O método deve **devolver** duas coisas, e neste momento não devolve nenhuma.
* Resposta 2:
  * Não é suposto usares HTML para mostrares a imagem, mas sim Markdown.
  * `FighterFactory` não contém instâncias de nada, pelo que não pode ter associações com nada.
* Resposta 3:
  * A resposta está mais próxima do que se pretende, mas neste caso a tua fábrica não é uma `interface`. O termo "interface" usado é mais geral (ou seja, não é necessariamente uma `interface`), por isso sugiro que uses a palavra interface sem ser em formatação de código, e completes a descrição com "define uma interface ou classe abstrata".
  * A frase tem um Português esquisito, falas em objeto a criar, mas depois já é classe a instanciar. Tens de ser mais preciso.
* Resposta 4:
  * Andas lá perto, mas essa explicação está muito confusa. Vê os slides em que falamos de polimorfismo, ou faz uma pesquisa no Google.
* Nas respostas 3 e 4 cita as fontes usadas.

2019-06-19 19:07 UTC, FPTheFluffyPawed commented
Utilizei HTML para a imagem, pois, queria ter a imagem centrada na resposta, pensava que ficaria melhor.

2019-06-19 19:37 UTC, nunofachada requested changes
* "mas deixa as subclasses decidir qual **a classe do objecto** a instanciar" (repara que a Wikipedia nem sempre está 100% correta)
* Na última resposta ficava bem um ponto final do meio daquela frase longa.

2019-06-19 20:00 UTC, nunofachada requested changes
* "class **a** instanciar"
* Ponto final no local errado na última frase.
* Podes ainda submeter correção a este problema agora após as 21h.

2019-06-20 11:15 UTC, merged

2019-06-20 11:16 UTC, fakenmc commented
Aceite. No último comentário queria dizer "classe **a** instanciar", e não "classe **a**...". Já corrigi na própria solução.