Proposta de solução 03_41
VideojogosLusofona/lp1_exercicios pull request #247
Opened 2020-02-29 19:53 UTC by FPTheFluffyPawed

Fiquei com uma dúvida na alínea 3. Não tenho a certeza se fiz bem. Era para utilizar o `CompareTo` nas verificações?

2020-03-02 12:46 UTC, nunofachada requested changes
* Adiciona os `using` em falta em cada classe.
* Na alínea 2, a classe `Program` não pode ser `private` (experimenta).
* Na alínea 2 falta uma chaveta para fechar o `Main`.
* Na alínea 3:
  * Porque razão comparas ambas as durabilidades com zero? Qual é o sentido disso?
  * O que acontece se a arma `x` ou a arma `y` forem `null`?
* Na alínea 4 falta colocares armas na lista para aparecer alguma coisa no ecrã.

Tanto na alínea 1 como na alínea 3 usas o método `CompareTo()` do tipo `float`, pois `float` implementa `IComparable<float>`. Não há problema nenhum. Geralmente usa-se a subtracção de um valor pelo outro, pois é mais eficiente, mas não precisa de mudar isso.

2020-03-02 23:01 UTC, nunofachada requested changes
* Os `using` que colocaste não resolvem o problema em nenhuma das alíneas.
* Continua a faltar uma chaveta de fecho na alínea 2. Além disso na alínea 2 é pedido um `Program` completo, portanto não faz sentido dizeres "Rest of the program goes here...".
* A alínea 3 agora não faz sentido. Além disso, se `x` ou `y` forem `null`, o programa crasha.
* Resumindo, tens de testar esta solução no Visual Studio ou `dotnet`, verificar as várias situações possíveis, incluindo com valores `null` na lista, e só depois voltar a submeter a solução.

2020-06-14 21:44 UTC, fakenmc commented
A resposta final para este problema pode ser submetida até ao final do dia de amanhã.

2020-06-15 19:20 UTC, nunofachada requested changes
Olá Inácio, agora funciona corretamente, mas o método `Compare()` da classe `Durability` podia ser mais simples, em particular a parte que vem a seguir a "Compare the items since they aren't null". Ou não?

2020-06-15 19:35 UTC, nunofachada requested changes
Não simplificaste, o código é o mesmo, mas mais compacto. Qual a razão sequer de teres um `if`? Porque não fazes como fizeste na aliena 1?

2020-06-15 19:40 UTC, FPTheFluffyPawed commented
Não sabia que podia simplificar desta forma, mas acho que fiz bem.

2020-06-15 19:45 UTC, fakenmc commented
A reposta está correta. Aqui não é uma questão de saberes, é uma questão de prática e chegares à conclusão que com esta simplificação a funcionalidade do código é exatamente a mesma.
Não posso aceitar já porque há um _merge conflict_. Faz _rebase_ deste teu ramo em cima do ramo _master_ e faz _push_ novamente. Por exemplo, estando neste ramo, faz `git pull --rebase`.

2020-06-15 19:45 UTC, fakenmc commented
O _push_ tens de o fazer com o parâmetro `-f`, pois o _rebase_ modifica a história.

2020-06-15 19:47 UTC, fakenmc commented
E quando fizeres um _rebase_ vais ter um conflito com a versão do teu colega. Eu quero que fiquem as duas versões, portanto podes deixar a dele como solução 1 e a tua como solução 2.

2020-06-15 19:50 UTC, FPTheFluffyPawed commented
Estou a fazer o _rebase_, mas diz que esta tudo atualizado quando estou em este _branch_.

2020-06-15 19:52 UTC, FPTheFluffyPawed commented
Espera, isto não é melhor fazer o rebase para 044?

2020-06-15 19:58 UTC, FPTheFluffyPawed commented
Desculpa, uma confusão enorme. Penso que esta resposta esta completa, mas isto do _rebase_ é para a solução 03_ex44. Deve ter confundido.

2020-06-15 21:13 UTC, merged

2020-06-15 21:13 UTC, fakenmc commented
Resposta aceite.