Proposta de solução 03_44
VideojogosLusofona/lp1_exercicios pull request #248
Opened 2020-02-29 22:37 UTC by FPTheFluffyPawed

2020-03-02 12:51 UTC, nunofachada requested changes
As respostas 2 e 3 estão erradas. Tens de pensar melhor nisso.

2020-03-02 19:58 UTC, nunofachada requested changes
* Resposta 2 continua errada. Pensa no problema em questão, não penses na teoria do C#. Aquela propriedade até poderia ser `private` e `static` ao mesmo tempo, e poderia continuar a ser útil. Qual é o propósito dela ser `static` e não uma variável de classe?
* Resposta 3 está melhor, mas tem coisas a mais. Podes simplificar.

2020-03-02 21:37 UTC, FPTheFluffyPawed commented
Na resposta 2, não é `static` porque assim existe só uma propriedade pertencente ao tipo?

2020-03-02 21:48 UTC, FPTheFluffyPawed commented
Espera. Não é melhor dito que é `static` para que seja único ao tipo, e que não seja parte das instâncias?

2020-03-02 22:55 UTC, fakenmc commented
É mais por ai. Pensa no seguinte, se o exercício pedi-se para teres um contador global de instâncias de `Enemy`, como resolverias o problema?

2020-06-14 21:44 UTC, fakenmc commented
A resposta final para este problema pode ser submetida até ao final do dia de amanhã.

2020-06-15 19:22 UTC, nunofachada requested changes
* Pergunta 2: essa razão não me convence. Quando é que faz sentido uma propriedade ou variável de classe ser `static`?
* Pergunta 3: "classe própria" -> "própria classe"

2020-06-15 19:34 UTC, FPTheFluffyPawed commented
Na pergunta 2: o sentido não é só para poder alterar essa variável sem ter de utilizar uma instância?

2020-06-15 19:35 UTC, fakenmc commented
> Na pergunta 2: o sentido não é só para poder alterar essa variável sem ter de utilizar uma instância?

Não. Isso muito raramente é razão para teres alguma coisa `static`. Ou mesmo nunca.

2020-06-15 19:40 UTC, FPTheFluffyPawed commented
Então,  a razão seria para ter uma variável partilhada por todas as instâncias então?

2020-06-15 19:41 UTC, fakenmc commented
> Então, a razão seria para ter uma variável partilhada por todas as instâncias então?

Por exemplo. Olha para o código. Faz sentido essa variável ser partilhada por todas as instâncias ou não? A variável representa algo a nível de uma instância ou a nível da classe (todas as instâncias)?

2020-06-15 19:44 UTC, FPTheFluffyPawed commented
> 
> 
> > Então, a razão seria para ter uma variável partilhada por todas as instâncias então?
> 
> Por exemplo. Olha para o código. Faz sentido essa variável ser partilhada por todas as instâncias ou não? A variável representa algo a nível de uma instância ou a nível da classe (todas as instâncias)?

A variável é algo ao nível da classe, então penso que faz sentido que seja `static`.

2020-06-15 19:46 UTC, fakenmc commented
Então força-

2020-06-15 20:01 UTC, FPTheFluffyPawed commented
Mesmo assim aqui com _rebase_ não funciona, diz que esta up-to-date.

2020-06-15 21:15 UTC, fakenmc commented
Podes resolver como quiseres, só posso aceitar a resposta após o conflito estar resolvido e ambas as soluções, a tua e a do teu colega, estarem presentes.

2020-06-15 21:19 UTC, merged

2020-06-15 21:19 UTC, fakenmc commented
Aceite.