Exercicio 33 Bases de CS, Solução
VideojogosLusofona/lp1_exercicios pull request #265
Opened 2020-04-11 17:56 UTC by NelsonSalvador

Isto foi também para treinar o git, o stor podia dar feedback se utilizei corretamente ou não sff

2020-04-11 18:07 UTC, nunofachada requested changes
Olá Nelson,

A resposta está correta, mas tens de melhorar o seguinte:

* O bloco de código começa e termina com três plicas \`\`\` e não quatro \`\`\`\`.
* Tem de haver uma linha em branco antes e depois do bloco de código. No teu caso falta essa linha em branco após o bloco de código.
* Deves melhorar (consideravelmente) o Português da última linha (usa o corretor do VS Code, e atenção à gramática), e deves fazer uso de formatação Markdown para ilustrar código (por exemplo, `if` e não if) e palavras em Inglês (por exemplo _array_ e não array).

2020-04-11 19:37 UTC, nunofachada requested changes
Está melhor, algumas alterações finais:

* No texto em linha, a formatação de código faz-se só com uma plica, por exemplo: \`if\`.
* Não ultrapasses os 80 carateres por linha. Um ENTER em Markdown não significa uma nova linha no documento resultante (para isso precisas de uma linha em branco).
* "Divisível" não começa com maiúscula. Para isso tinha de estar no início de uma frase, após um ponto final.

2020-04-12 17:55 UTC, nunofachada requested changes
Está quase, mas não é preciso a linha em branco entre cada uma das frases, pois isso vai provocar um ENTER no documento gerado. A ideia é cada linha no Markdown ter no máximo 80 carateres, e não que isso aconteça no documento gerado.

2020-04-12 19:24 UTC, NelsonSalvador commented
Ah já percebi, interpretei mal vou trocar agora

2020-04-12 19:26 UTC, merged

2020-04-12 19:26 UTC, fakenmc commented
Solução aceite.