Ex31 BasesCs, NelsonSalvador
VideojogosLusofona/lp1_exercicios pull request #266
Opened 2020-04-12 14:27 UTC by NelsonSalvador

2020-04-12 15:05 UTC, fakenmc commented
Nelson, termina os detalhes no exercício anterior, e depois voltamos a este.

2020-04-12 15:07 UTC, fakenmc commented
Em todo o caso, para este posso dizer-te que deves copiar o código Markdown do enunciado do exercício (repara que só copiaste o texto e perdeste a formatação e estás a ultrapassar os 80 carateres por linha).
Além disso podes incluir os conteúdos completos do `Program.cs`.

2020-04-12 18:06 UTC, nunofachada requested changes
Boa primeira tentativa com este problema. Alguns reparos:

* _n_ é o número de linhas e _m_ o número de colunas. Parece-me que trocaste.
* O vetor deve ter dimensão _n_, como indicado no enunciado, e não _m_. Está trocado também.
* Os conteúdos da matriz e do vetor devem ser números reais e não apenas inteiros.
* Falta uma linha em branco após o fim do bloco de código.

2020-04-12 19:10 UTC, NelsonSalvador commented
Okay professor, mas no site que está no markdown diz o contrário, (n numero de colunas) 
https://mathinsight.org/matrix_vector_multiplication

2020-04-12 19:12 UTC, fakenmc commented
O site é apenas para verificarem se o programa funciona. No entanto devem responder de acordo com o que está pedido no enunciado.

2020-04-12 19:16 UTC, NelsonSalvador commented
okay professor eu vou trocar, mas eu pesquisei mais e n é normalmente as colunas e m as linhas, no enunciado não dizia qual era qual por isso é que eu fiz assim.

2020-04-12 19:17 UTC, fakenmc commented
No enunciado diz _n_ x _m_ e por convenção primeiro vem as linhas e depois as colunas. Em todo o caso é de facto mais comum ser _m_ por _n_, por isso provavelmente atualizo eu o enunciado. Deixa-me confirmar.

2020-04-12 19:26 UTC, fakenmc commented
No livro de IMFJ1&2 usam _r_ x _c_, e outros livros usam notação diferente. Por isso mantém a notação que está no enunciado: _n_ x _m_. O mais importante é o primeiro valor referir-se a linhas e o segundo referir-se a colunas.
No entanto, como referiste, é mais comum ser _m_ x _n_, mas altera em conformidade com o enunciado.

2020-04-12 19:28 UTC, NelsonSalvador commented
Okay professor, obrigada pelo feedback

2020-06-14 21:43 UTC, fakenmc commented
A resposta final para este problema pode ser submetida até ao final do dia de amanhã.

2021-04-13 14:59 UTC, closed without merging