Exercicio 44, POO, Solução 1 - Luiz Santos
VideojogosLusofona/lp1_exercicios pull request #272
Opened 2020-06-13 21:30 UTC by JundMaster

Proposta de solução do exercício 44 de POO.

2020-06-13 23:24 UTC, nunofachada requested changes
* A resposta à pergunta 1 está incompleta.
* Quase no final da resposta 2 podes melhorar a pluralidade de algumas palavras.

2020-06-13 23:58 UTC, JundMaster commented
Olá professor,

O push com as correções já está feito.

2020-06-14 21:39 UTC, nunofachada requested changes
* Imprimir `NumberOfEnemies` da forma que indicas está incorreto. Nota que se trata de uma propriedade `static`, está definida ao nível da classe e não das instâncias.
* Encontrei um erro de Português na resposta 3.

2020-06-15 02:02 UTC, JundMaster commented
Olá professor,

As alterações solicitadas estão feitas.

2020-06-15 10:22 UTC, merged

2020-06-15 10:22 UTC, fakenmc commented
Olá Luiz, solução aceite.