added first solution bases_cs 35
VideojogosLusofona/lp1_exercicios pull request #39
Opened 2019-03-21 23:23 UTC by RafaelCS-Aula

2019-03-21 23:47 UTC, nunofachada requested changes
* Num programa, primeiro que tudo devem ser declaradas as variáveis. Neste caso tens variáveis declaradas ao longo do programa, o que não é boa prática.
* Ainda não falámos sobre o método `Parse()`. Até pode ficar assim, mas para benefício dos teus colegas vou colocar uma nota a indicar que nesta fase do campeonato não é suposto saberem resolver o problema desta forma.
* No último `Console.WriteLine()` falta-te uma vírgula a separar a última aspa e a variável `c`. Em todo o caso estás a misturar concatenação com formatação ao estilo `printf` do C, o que não é boa ideia, pois torna o código mais difícil de ler. Neste caso será boa ideia apenas usares a formatação ao estilo `printf` com dois _placeholders_ para variáveis (que por acaso são a mesma, `c` e `c`). Em alternativa podes usar uma _string_ interpolada.

2019-03-21 23:50 UTC, RafaelCS-Aula commented
Pode esclarecer um pouco o ultimo ponto se faz favor?
Eu nunca mexi em C, só entrei no curso este semestre.

2019-03-21 23:58 UTC, fakenmc commented
Quando refiro o estilo `printf` quero dizer indicares as variáveis ou valores após a _string_, por exemplo:

```cs
Console.WriteLine("x igual a {0}, y igual a {1}", x, y);
```

Misturares este estilo de formatação com concatenação (usar o `+` para juntar _strings_) torna o código difícil de ler.

2019-03-22 00:01 UTC, RafaelCS-Aula commented
Desta maneira seria aceitável?

``` Console.WriteLine("It becomes: {0}, turn it into hex: 0x{0:x}", c);```

2019-03-22 00:02 UTC, fakenmc commented
Sim.

2019-03-22 00:05 UTC, RafaelCS-Aula commented
OK obrigado.

2019-03-22 18:32 UTC, merged

2019-03-22 18:32 UTC, fakenmc commented
Obrigado, solução aceite.