Made the game, first attempt at solution for bases_cs 30
VideojogosLusofona/lp1_exercicios pull request #40
Opened 2019-03-22 01:41 UTC by RafaelCS-Aula

A aplicação crasha se o jogador tenta sair do mapa, técnicamente não passa os limites... i guess.

Não tenho bem a certeza de como arranjar isso...

2019-03-22 18:46 UTC, nunofachada requested changes
* Ao divisão de `mapWidth` e `mapHeight` por 2 é entre tipos inteiros, pelo que a divisão dá um resultado inteiro. Assim sendo o cast para `double` e o `Math.Floor()` não fazem nada.
* Se a ideia do `mapWidth` e `mapHeight` é apenas determinar o local onde vais colocar o jogador, escusas de ter essas variáveis. Usas diretamente `playerX ` e `playerY`. 
* É necessário corrigires indentação, podes fazê-lo com CTRL+K+D no Visual Studio. Poderá ser mais fácil copiares todo o texto do ficheiro `Program.cs` para não estares a indentar manualmente ao inserir aqui na solução.
* Como disse nas aulas, não é permitido usar o tipo `var`. Mete o rato por cima de `Key` para saberes qual o seu tipo exato.
* Em todo o caso neste problema bastava usares o `Console.Readline()`, uma vez que não discutimos as técnicas usando `Console.ReadyKey()`. A única desvantagem é que o "jogo" ficaria menos interativo, pois requer pressionar o ENTER a seguir à tecla WASDQ. No entanto se optares por manter esta abordagem aceito perfeitamente, vou é colocar uma nota com indicação de que não demos ainda essa matéria.
* Estás a misturar a criação da grelha com a sua visualização. Num `for` deves criar a grelha para a _turn_ atual (preenchendo o _array_ bidimensional_ com `.` e `@`), e noutro `for` deves imprimi-la. Misturar as duas coisas geralmente dá problemas.
* O jogo _crasha_ porque não estás a verificar se o jogador se move para além dos limites da grelha. Tens de fazer essa verificação.

2019-03-23 03:23 UTC, RafaelCS-Aula commented
Manti a ´mapWidth´ e ´mapHeight´ porque as uso para definir o tamanho do mapa, nos _loops_ `for` para encher o `mapa[,]` e depois o desenhar; e no fim para garantir que o `player` não sái dos limites do mapa e _crash_ aquilo tudo.

2019-03-24 18:13 UTC, nunofachada requested changes
Olá Rafael, a solução está boa, peço apenas as seguintes alterações essencialmente relacionadas com boas práticas de organização de código:

* Remover `using`s desnecessários.
* Em C#, os conteúdos de cada `case` normalmente estão indentados 4 espaços. Quando fazes CTRL+K+D no Visual Studio ele não te faz isso automaticamente?
* Colocar um espaço entre o início do comentário `//` e a primeira palavra do mesmo.
* Evitar ter duas ou mais linhas em branco.

2019-03-24 18:52 UTC, RafaelCS-Aula commented
Quanto á indentação dos `case`s, eu fiz CTRL+K+D várias vezes no visual studio e foi assim que eles ficaram. Devo fazê-lo manualmente?

2019-03-24 19:11 UTC, fakenmc commented
É estranho, pois no C# a indentação é como referi e não como está, embora exista malta que prefira como está (alguma malta do C e do Java). Não creio que valha a pena mudar. Vou aceitar.

2019-03-24 19:11 UTC, merged

2019-03-24 19:13 UTC, RafaelCS-Aula commented
OK, obrigado