Exercicio 23 Calculadora BasesCs
VideojogosLusofona/lp1_exercicios pull request #49
Opened 2019-03-25 22:52 UTC by AnSantos99

2019-03-26 15:05 UTC, nunofachada requested changes
Olá Ana,

A ideia é que o operador e operandos sejam passados como argumentos no terminal/linha de comandos. Ou seja, deves executar a calculadora da seguinte forma (no cmd, Windows Powershell ou Git Bash):

`dotnet run / 6 3` (para dividires 6 por 3)

Portanto não deves pedir nada ao utilizador diretamente. Outra coisa, mais uma questão de estilo. Nos comentários, é boa prática colocares um espaço entre o início do comentário `//` e o texto propriamente dito.

2019-03-26 15:07 UTC, fakenmc commented
Outra coisa, atualizei o enunciado para invocares o programa com `dotnet run` (é como se faz no .NET Core) e não com `Calc.exe` (era como se fazia no .NET Framework). Se quiseres podes também atualizar o enunciado na tua solução.

2019-03-27 00:32 UTC, AnSantos99 commented
Boa noite Stor,
Consegui fazer todas as alterações pedidas, mas tenho uma pergunta. Quando se faz alterações e push do ficheiro que está no estado open de pull request é necessário fazer outro pull request ou as alterações ficam automaticamente nesse pull request. Porque eu vi que no tab (commits) está a alteração que fiz ao ficheiro lá dentro só que, não sei se isso é só visível para mim ou se você também consegue ver essa alteração nova.
Obrigado

2019-03-27 10:33 UTC, fakenmc commented
Olá Ana, quando fazes _push_ de _commits_ num ramo que esteja no estado de _pull request_ aberto, não é preciso fazeres mais nada, que eu vejo as alterações.

Em todo o caso, relativamente à inserção das operações, as alterações que fizeste não são as pretendidas, pois o utilizador ainda tem de inserir o operador e números quando o programa é executado. A ideia é que a operação seja feita automaticamente usando os argumentos passados na linha de comandos **no momento em que invocas o programa**. Por exemplo, se executares o seguinte comando:

`dotnet run + 5 3`

o programa automaticamente imprime `8`. Os argumentos da linha de comandos estão no _array_ `args`, que é um parâmetro da função `Main()`. Falámos disto na 1ª e 3ª aulas.

2019-04-01 15:12 UTC, AnSantos99 commented
Boa tarde Professor, 
Com a ajuda da colega Diana Levay consegui fazer que utilizador ao escrever os 3 argumentos obtenha o resultado da conta mas, surgiu um problema. O utilizador consegue fazer contas com as operações `+` e `p` mas ao tentar fazer com as restantes operações o programa dá este erro  _Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array._ 
Eu penso que o problema é que o programa não reconheçe as posições onde os argumentos estão (nas linhas 34, 35, 36 no args[0] args[1] args[2]).
Obrigado

2019-04-01 16:24 UTC, nunofachada requested changes
Olá Ana, está quase, falta apenas indicares uma mensagem de erro apropriada quando o utilizador insere menos ou mais de três argumentos.

2019-04-05 06:51 UTC, AnSantos99 commented
Bom dia Professor,
Consegui meter o ciclo no caso de o utilizador inserir + ou - argumentos só ainda é que não consegui entender bem porque que o símbolo da operação `*` e a operação `-` não estão a ser reconhecidas pelo git Bash nem pelo cmd. Tentei substituir os símbolos com letras para ver se o problema era no ciclo switch case mas quando testei isso a operação estava a funcionar e fiquei um pouco confusa.
Obrigado

2019-04-05 07:21 UTC, fakenmc commented
Olá Ana,

As operações com alguns símbolos são transformadas noutras coisas, para evitares isso é preciso colocar  o símbolo entre aspas, e executar assim: `dotnet run "*" 3 4`

Outra coisa, tens o seguinte erro: `Operator '!=' cannot be applied to operands of type 'string' and 'char'`. Este erro ocorre no `if` em que verificas se o operador é válido. Consegues perceber porquê?

2019-04-05 16:13 UTC, AnSantos99 commented
Boa tarde Professor,
Sim porque enganei-me nas peliculas na comparação do if em vez de usar `"!="` assim o programa da erro porque não consegue comparar um tipo string com um tipo char. Vou já corrigir.
Obrigado

2019-04-05 22:25 UTC, nunofachada requested changes
Olá Ana,

* Ao inserires menos ou mais de três elementos, o programa _crasha_ eventualmente. Uma forma de resolveres isso é terminares o programa com `Environment.Exit(0);` após a tua mensagem de erro, tal como fazes no caso da operação desconhecida (embora possas simplesmente usar `return` nos dois casos, pois é mais simples e óbvio).
* Adiciona a tua assinatura no fim, como os teus colegas têm feito nos outros exercícios.

Outra coisa, já percebi o teu problema no sinal `-`. O programa `dotnet` assume isso como uma opção dele próprio e não como opção a passar ao programa. Podes resolver isso colocando `--` após o comando `dotnet run`, e só depois indicares as opções para o programa, desta forma:

```
dotnet run -- - 5 3
```

No caso da multiplicação o caráter `*` é automaticamente convertido noutra coisa, pelo que é mesmo necessário colocá-lo entre aspas.

2019-04-07 20:14 UTC, AnSantos99 commented
Boa noite professor,
Eu substitui nos Ifs o `Enviroment exit()` por `return`. Gostava de saber o que o return faz neste caso. Eu penso que o return como não retorna nada, o programa acaba. Mas gostava de saber neste caso qual é a diferença em usar o enviromente exit() e o return. Enquanto às operações já testei e funcionou.
Obrigado

2019-04-07 20:55 UTC, merged

2019-04-07 20:58 UTC, fakenmc commented
Olá Ana, no `Main()` o `return` faz o mesmo que nos outros métodos: sai do método, possivelmente devolvendo um valor a quem o chamou. Neste caso como o `Main()` é chamado diretamente da linha de comandos, o programa simplesmente retorna para a linha de comandos, ou seja, termina. Não devolvemos valor nenhum pois o `Main()` tem um valor de retorno `void`.

Aceitei a solução, mas fiz uma pequena melhoria na formatação da tua assinatura, confere.