Feito exercício 26, algumas dúvidas na parte da probabilidade (chance)
VideojogosLusofona/lp1_exercicios pull request #85
Opened 2019-04-09 17:21 UTC by JBernardoRebelo

2019-04-09 17:55 UTC, nunofachada requested changes
Olá João, são necessárias várias alterações:

* O número de _turns_ deve ser dado como argumento na linha de comandos (na variável `args`). Não é suposto ser pedido ao utilizador.
* Sendo `rng` uma variável, porque razão não está a ser declarada na zona de declaração de variáveis?
* Se `live` tem apenas dois valores, porque razão não é um booleano?
* Na questão da probabilidade, tens de verificar se o valor aleatório obtido é **menor** que 0.02 (2%). Garanto-te que nunca vai ser igual a 0.02, nem que corras o programa 500x. Basicamente o método `NextDouble()` retorna um valor entre 0 e 1, sendo que existe 2% de possibilidade de ser menor que 0.02 e 98% de possibilidade de ser maior que 0.02 (pois 1 - 0.02 = 0.98).
* Na forma como tens estruturado o programa, vai aparecer a mensagem a dizer `Player has survived...` mesmo que ele tenha morrido ali mesmo. Não tenhas medo de usar o `break` se der mesmo jeito.
* Se facilitar podes copiar todo o código da classe `Program`, assim escusas de estar sempre a indentar quando copias para o ficheiro Markdown da solução.
* Falta um espaço entre "##" e "Problema", senão aparece desformatado, como podes ver [aqui](https://github.com/VideojogosLusofona/lp1_exercicios/blob/9ddad58e23313f17dfea7f74f5d3b6ae14072dac/solucoes/02_bases_cs/26.md).
* O enunciado foi mal copiado. O mais fácil é copiares o Markdown diretamente em vez de estares a tentar formatar tu. Entre outras coisas, _turn-based_ não aparece em itálico e falta a parte final do enunciado (as notas, etc).

Por último, tens outro _pull request_ aberto à espera de conclusão, é preferível corrigires o que está pendente do que estares a abrir novos _pull requests_.

2019-04-10 18:29 UTC, nunofachada requested changes
João, são necessárias as seguintes alterações:

* Todo o programa tem uma indentação a mais. Copia mesmo o `using System;` e o _namespace_, pois assim escusas de estar a indentar à mão.
* Não aprendemos excepções ainda. Podias ter ignorado a situação de não ter sido dado um argumento, ou ter resolvido a mesma com um `if` perguntando se o tamanho do _array_ de argumentos é igual a 1. Vou deixar estar, até para colegas teus submeterem abordagens diferentes, mas depois colocarei um aviso com indicação de que não demos excepções. É verdade no entanto que a excepção te permite apanhar o caso em que o utilizador insere algo não convertível para inteiro, mas mesmo isso também podia ter sido feito à mão, ou ter sido ignorado.
* O comentário `As long as the number of lives is 1...` já não faz sentido dado a abordagem que usas agora.
* Pensa bem no que significa `live = true` dentro do `while`. Nota que não está a ser feita uma comparação, mas sim uma atribuição. Além disso, `live` é um booleano, logo pode ser usado diretamente como condição.
* A palavra "turns" que aparece nas mensagens começa com minúscula.
* Para que servem as condições no `while` se as vais voltar a verificar nos `ifs` dentro do `while`?
* Por favor adiciona o email com o qual fizeste estes _commits_ (bernasfattaker gmail) à tua conta do GitHub, de modo a pareceres na [lista de contribuidores](https://github.com/VideojogosLusofona/lp1_exercicios/graphs/contributors).

2019-04-10 19:21 UTC, JBernardoRebelo commented
Sobre os ifs dentro do while, tomei essa decisão pois sempre que saía do while ele incrementava turns e o output não correspondia ao número de turns realmente passadas pelo jogador, numa solução antes de enviar a primeira vez, decrementava o turns cada vez que saía do while para o output bater certo. De certeza que existe uma resolução a que não estou a chegar, mas por agora decidi fazer desta forma.

2019-04-10 22:11 UTC, fakenmc commented
* Porque não metes `turns++` dentro de um `else` (isto é, é incrementado quando `turns` for diferente de `maxturns`), e resolves o problema?
* Remove linha em branco (última linha dentro do bloco de código).
* Ainda não apareces na lista de contribuidores, é possível que o GitHub demore um bocado a atualizar isso.

2019-04-11 16:56 UTC, nunofachada requested changes
Agora o jogador sobrevive sempre na _turn_ 1... estás a complicar :/

2019-04-11 16:56 UTC, nunofachada requested changes
Agora o jogador sobrevive sempre na _turn_ 1... estás a complicar :/

2019-04-11 16:56 UTC, nunofachada requested changes
Agora o jogador sobrevive sempre na _turn_ 1... estás a complicar :/

2019-04-11 18:58 UTC, nunofachada requested changes
Está funcionalmente correto agora, mas pergunto-te: para que serve a variável `live` neste momento?

2019-04-12 18:24 UTC, nunofachada requested changes
João, experimenta lá correr o programa...

2019-04-13 12:32 UTC, fakenmc commented
Obrigado João, solução aceite.

2019-04-13 12:34 UTC, merged

2019-04-13 12:49 UTC, fakenmc commented
João, verifica de novo se as tuas diferentes contas de email estão bem configuradas nos _Settings_ da tua conta do GitHub. Como vês na imagem em baixo, tenho diferentes contas de email configuradas, de modo a todos os _commits_ que faço para diferentes projetos serem associados à minha conta do GitHub:
![image](https://user-images.githubusercontent.com/3018963/56079939-fd05df00-5df2-11e9-873a-ae72a1161e09.png)