Ex36 bases cs, versão corrigida
VideojogosLusofona/lp1_exercicios pull request #95
Opened 2019-04-11 17:47 UTC by PmaiWoW

2019-04-11 18:50 UTC, nunofachada requested changes
* Onde estão os cabeçalhos **## Problema** e **## Soluções**?
* O _link_ para as soluções pode ser obviamente removido.
* Neste caso um jogador não pode ter mais do que uma classe. Além disso não ser pedido, podes chegar a essa conclusão pelo facto de eu pedir para usares um `switch`. Ou seja, neste caso não faz sentido usares _enumeration flags_.
* Nesse mesmo sentido, o nome da enumeração não deve ser  `Classes`, mas algo no singular, pois representa **uma** classe.
* Uma vez que o jogador pode ter apenas uma classe, deixa de ser necessário teres aquele ciclo `while`.
* A ideia é fazeres converteres a resposta do utilizador num valor da enumeração, depois usares o `switch` nesse mesmo valor, e finalmente cada `case` deve comparar um valor da enumeração (e.g. `case Classe.Druid:`).

2019-04-12 18:19 UTC, nunofachada requested changes
* Uma enumeração, sendo um tipo, deve começar com maiúscula.
* Tens um problema de indentação no primeiro `break`.
* Em vez de fazeres _cast_ em todos os cases, porque não convertes o _input_ do utilizador num valor da enumeração, fazendo depois o `switch` numa variável do tipo `RpgClass`?

2019-04-13 09:39 UTC, PmaiWoW commented
Tive que pesquisar uma forma de fazer a conversão do input para enumeração e encontrei o enum.parse, se não for para fazer a conversão desta forma caso haja outra mais adequada depois procuro-a e alterarei a solução

2019-04-13 10:00 UTC, PmaiWoW commented
Peço desculpa, apaguei por engano o ramo mas já foi restaurado

2019-04-13 13:00 UTC, fakenmc commented
Pedro, o projeto tem erros, que devem estar realçados no Visual Studio. Em todo o caso a forma que utilizaste para fazer a conversão está correta, fizeste uma boa pesquisa, mas assume que `playerInput` é uma _string_ e no teu caso tens um `int`. Aliás, é por isso que o projeto apresenta erros no Visual Studio.

Outra forma que tens de converter uma _string_ num valor da enumeração é converteres a _string_ para inteiro e depois simplesmente fazeres um _cast_ desse inteiro para o tipo da enumeração, por exemplo:

```cs
string playerInput = Console.ReadLine();
int input = Convert.ToInt32(playerInput);
RpgClass rpgClass = (RpgClass) input;
```

Em todo o caso, a tua abordagem também está correta.

2019-04-13 18:22 UTC, PmaiWoW commented
Já vi o problema, no meu funcionava bem porque tinha substituído certos elementos já e não atualizei no documento da solução, como foi o caso do playerInput passar de string para int, entreguei porque no visual studio dava mas não fiz todas as alterações no documento da solução, também iria haver um erro no WriteLine da class após mudar o playerInput, mas já foi resolvido pois deve mostrar plyrClass em vez do playerInput

2019-04-14 14:56 UTC, fakenmc commented
Obrigado Pedro, solução aceite.

2019-04-14 14:57 UTC, merged